import {bootstrap,load,transact,runtime} from '@/lib/supabase-store';
import {identity,login,callback,session,isDemo,logout} from '@/lib/supabase-auth';
import {mutate,view,check,find,role,archived,uid,now,runRecurrences,AppError} from '@/lib/model';
import {demo} from '@/lib/demo';
export const dynamic='force-dynamic';
const json=(x:any,status=200)=>Response.json(x??{ok:true},{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
async function sendInvite(i:any){const e=runtime();if(e.DEMO_MODE==='true')return;try{check(e.RESEND_API_KEY&&e.INVITE_FROM&&e.APP_ORIGIN,'Invitation email service is not configured',503);const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+e.RESEND_API_KEY,'Content-Type':'application/json','User-Agent':'AspireOne-Connect/0.1','Idempotency-Key':i.id+'-'+i.token.slice(0,12)},body:JSON.stringify({from:e.INVITE_FROM,to:[i.email],subject:'Your invitation to AspireOne Connect',text:`You have been invited to AspireOne Connect with ${i.role} access. Sign in with ${i.email} to accept your invitation: ${e.APP_ORIGIN}/?invite=${encodeURIComponent(i.token)}\nThis invitation expires in seven days.`})});check(response.ok,response.ok?'':await emailError(response),502);await transact(s=>{find(s,'invites',i.id).delivery='sent';});}catch(error){console.error('Invitation delivery failed',i.id,error);await transact(s=>{find(s,'invites',i.id).delivery='failed';});throw error;}}
async function handler(r:Request){try{const path=new URL(r.url).pathname.replace('/api/',''),e=runtime();if(r.method==='POST'){check(r.headers.get('Origin')===new URL(r.url).origin||((path==='scheduler')&&r.headers.get('Authorization')==='Bearer '+e.CRON_SECRET),'Request origin rejected');}
 if(path==='auth/login')return await login(r);if(path==='auth/callback')return await callback(r);
 if(path==='config')return json({demo:false,google:!!e.SUPABASE_PUBLISHABLE_KEY});
 if(path==='demo'&&r.method==='POST'){check(isDemo(r),'Demo login is disabled',404);await bootstrap();await transact(demo);const p:any=await r.json();const {state}=await load();const u=state.users.find(u=>u.id===p.user);check(u&&u.id.startsWith('demo-'),'Unknown demo account',400);return new Response('{}',{headers:{'Content-Type':'application/json','Set-Cookie':await session(r,u)}});}
 if(path==='scheduler'&&r.method==='POST'){check(e.CRON_SECRET&&r.headers.get('Authorization')==='Bearer '+e.CRON_SECRET);return json({generated:await transact(s=>runRecurrences(s))});}
 const user=await identity(r);
 if(path==='auth/logout'&&r.method==='POST')return await logout(r);
 if(path==='state'&&r.method==='GET'){const {state,revision}=await load();return json({...view(state,find(state,'users',user.id)),revision,demo:isDemo(r)});}
 if(path==='action'&&r.method==='POST'){check(Number(r.headers.get('content-length')||0)<500000,'Request too large',413);const p:any=await r.json();const result=await transact(s=>mutate(s,find(s,'users',user.id),p));if((p.op==='invite'||p.op==='invite.update')&&!p.cancel){await sendInvite(result);return json({ok:true});}return json(result);}
 if(path==='upload'&&r.method==='POST'){const limit=Number(e.UPLOAD_LIMIT_MB||25)*1024*1024;check(Number(r.headers.get('content-length')||0)<=limit+100000,'File exceeds upload limit',413);const form=await r.formData(),file=form.get('file') as File,board=String(form.get('board')),subject=String(form.get('subject'));check(file&&typeof file.arrayBuffer==='function'&&file.size>0&&file.size<=limit,'File must be within the upload size limit',400);const ext=file.name.split('.').at(-1)?.toLowerCase()||'';const types:Record<string,string>={png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',pdf:'application/pdf',txt:'text/plain',csv:'text/csv',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document',xls:'application/vnd.ms-excel',xlsx:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',ppt:'application/vnd.ms-powerpoint',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation'};check(types[ext]&&(!file.type||file.type===types[ext]||(['csv','txt'].includes(ext)&&file.type==='text/plain')),'Unsupported file type',400);const bytes=new Uint8Array(await file.arrayBuffer());const sig=(v:number[])=>v.every((n,i)=>bytes[i]===n);check((ext==='pdf'?sig([37,80,68,70]):ext==='png'?sig([137,80,78,71]):['jpg','jpeg'].includes(ext)?sig([255,216,255]):ext==='gif'?sig([71,73,70,56]):ext==='webp'?sig([82,73,70,70])&&String.fromCharCode(...bytes.slice(8,12))==='WEBP':['docx','xlsx','pptx'].includes(ext)?sig([80,75,3,4]):['doc','xls','ppt'].includes(ext)?sig([208,207,17,224,161,177,26,225]):!bytes.includes(0)),'File contents do not match the selected type',400);
 const {state}=await load();check(role(state,user,board)>0);const ctx=state.tasks.find(t=>t.id===subject)||state.topics.find(t=>t.id===subject);check(ctx&&ctx.board===board,'Conversation unavailable',404);check(!find(state,'boards',board).archived&&(!ctx.group||!archived(state,ctx)),'Restore archived work before uploading',400);const id=uid(),key=board+'/'+uid(),name=file.name.replace(/[^\p{L}\p{N}._ -]/gu,'_').slice(0,180);await e.BUCKET.put(key,bytes,{httpMetadata:{contentType:types[ext]}});try{await transact(s=>{const current=find(s,'users',user.id);check(role(s,current,board)>0);const context=s.tasks.find(t=>t.id===subject)||s.topics.find(t=>t.id===subject);check(context&&(!context.group||!archived(s,context))&&!find(s,'boards',board).archived);s.files.push({id,key,board,subject,name,size:file.size,type:types[ext],user:user.id,at:now(),removed:false});});}catch(err){await e.BUCKET.delete(key);throw err;}return json({id,name,size:file.size});}
 if(path.startsWith('files/')&&r.method==='GET'){const {state}=await load(),f=find(state,'files',path.split('/')[1]);check(role(state,user,f.board)>0);check(!f.removed&&(!f.message?f.user===user.id:!find(state,'messages',f.message).removed),'Attachment unavailable',404);const obj=await e.BUCKET.get(f.key);check(obj,'File unavailable',404);const inline=new URL(r.url).searchParams.get('preview')==='1'&&['image/png','image/jpeg','image/gif','image/webp','application/pdf'].includes(f.type);return new Response(obj.body,{headers:{'Content-Type':f.type,'Content-Disposition':`${inline?'inline':'attachment'}; filename*=UTF-8''${encodeURIComponent(f.name)}`,'Cache-Control':'private, no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"sandbox; default-src 'none'"}});}
 return json({error:'Not found'},404);
 }catch(error){if(!(error instanceof AppError))console.error('Portal request failed',error);return json({error:error instanceof AppError?error.message:'Service unavailable. Your draft has been preserved. Please retry.'},error instanceof AppError?error.status:503);}}
export const GET=handler;export const POST=handler;
import {emailError} from '@/lib/email-error';
