import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();await db.exec('create role anon; create role authenticated; create role service_role;');
const root=new URL('../',import.meta.url).pathname;
await db.exec(fs.readFileSync(root+'deployment/supabase-planning.sql','utf8'));
const sql=fs.readFileSync(root+'deployment/supabase-planning-v2.sql','utf8');await db.exec(sql);await db.exec(sql);
const id='c0000000-0000-4000-8000-000000000003';
const save=async(kind,id,revision,data)=>(await db.query('select public.ao_planning_save($1,$2,$3,$4,$5) as saved',[kind,id,revision,'tester',JSON.stringify(data)])).rows[0].saved;
const source=(await db.query('select * from ao_plan_prices')).rows[0];assert.equal(source.payload.prices.length,104);assert.equal(source.published_data,null);
const initial={name:'Prices',effective_date:'2027-01-01',payload:source.payload,status:'published'};
let r=await save('prices',id,1,initial);assert.equal(r.revision,2);assert.equal(r.published_data.payload.prices[0].amount,9200);
const edited=structuredClone(initial);edited.status='draft';edited.name='Private draft';edited.payload.prices[0].amount=9900;
r=await save('prices',id,2,edited);assert.equal(r.payload.prices[0].amount,9900);assert.equal(r.published_data.payload.prices[0].amount,9200);assert.equal(r.published_data.name,'Prices');
await assert.rejects(save('prices',id,2,edited),/CONFLICT/);
r=await save('prices',id,3,{...edited,status:'published'});assert.equal(r.published_data.payload.prices[0].amount,9900);assert.equal(r.revision,4);
await db.exec(sql);assert.equal((await db.query('select payload from ao_plan_prices')).rows[0].payload.prices[0].amount,9900);
const b={name:'Budget',entity_id:'c0000000-0000-4000-8000-000000000001',year:2027,status:'published',payload:{lines:[]},rules_snapshot:{prices:[]}};
let budget=await save('budget',null,0,b);assert.equal(budget.published_data.name,'Budget');budget=await save('budget',budget.id,1,{...b,name:'Unpublished revision',status:'draft'});assert.equal(budget.published_data.name,'Budget');assert.equal(budget.name,'Unpublished revision');
await assert.rejects(save('budget',budget.id,2,{...b,entity_id:'c0000000-0000-4000-8000-000000000002'}),/cannot change/);
assert.equal((await db.query('select count(*)::int as n from ao_plan_audit')).rows[0].n,5);
assert.equal((await db.query("select name from ao_plan_entities where kind='branch'")).rows[0].name,'Physical Centre');
await db.exec('set role authenticated');await assert.rejects(db.query('select * from ao_plan_prices'),/permission denied/);await assert.rejects(save('prices',id,4,edited),/permission denied/);
console.log('PASS: separate tables; rerunnable import; two entities; draft/publication isolation; republish same record; optimistic conflicts; audit; budget snapshots; direct browser access denied.');await db.close();
