'use client';
import {useEffect,useState} from 'react';
import {businessRoles} from '../lib/business-roles';
const call=async(path:string,data?:any)=>{const r=await fetch('/api/'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:undefined);if(!r.ok)throw new Error(((await r.json()) as any).error||'Request failed');return r.json() as Promise<any>;};
export function RoleChecks({value,onChange}:{value:string[];onChange:(v:string[])=>void}){return <div className="role-checks">{businessRoles.map(r=><label key={r}><input type="checkbox" checked={value.includes(r)} onChange={e=>onChange(e.target.checked?[...value,r]:value.filter(x=>x!==r))}/>{r}</label>)}</div>;}
export function BoardRoleAccess({board,act}:any){const [grants,setGrants]=useState<Record<string,string>>(board.roleAccess||{}),[busy,setBusy]=useState(false);useEffect(()=>setGrants(board.roleAccess||{}),[board.version]);return <section><h3>Access by role</h3><p>Everyone holding a role receives its access. The strongest individual or role permission applies.</p>{businessRoles.map(r=><label className="role-grant" key={r}>{r}<select value={grants[r]||''} onChange={e=>{const next={...grants};if(e.target.value)next[r]=e.target.value;else delete next[r];setGrants(next);}}><option value="">No role access</option><option>View</option><option>Edit</option><option value="Manage">Manager</option></select></label>)}<button disabled={busy||board.archived} onClick={async()=>{setBusy(true);try{await act({op:'board.roles',board:board.id,version:board.version,grants});}catch{}finally{setBusy(false);}}}>Save role access</button></section>;}
function ArticleEditor({article,board,act,close}:any){
 const [draft,setDraft]=useState<any>(article?{...article,audience:article.audience==='all'?[...businessRoles]:[...new Set(['Director',...(article.audience||[])])]}:{title:'',description:'',publishDate:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'}),tags:[],audience:['Director'],pinned:false});
 const [attachments,setAttachments]=useState<any[]>(article?.attachmentInfo|| (article?.content?[{id:article.content,name:'Full article',type:article.contentType}]:[]));
 const [uploads,setUploads]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const field=(key:string,value:any)=>setDraft({...draft,[key]:value});
 return <form className="article-editor panel detail-body" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const files=[...attachments];for(const file of uploads){const form=new FormData();form.append('board',board.id);form.append('file',file);const response=await fetch('/api/article-content',{method:'POST',body:form});const result=await response.json() as any;if(!response.ok)throw new Error(result.error||'Upload failed');files.push(result);setAttachments([...files]);setUploads(v=>v.filter(f=>f!==file));}const content=files.find(f=>['text/html','application/pdf'].includes(f.type))?.id||files[0]?.id;await act({op:'article.save',...draft,board:board.id,content,attachments:files.map(f=>f.id)});close();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <h2>{article?'Edit article':'New article'}</h2><label>Title<input required maxLength={200} value={draft.title} onChange={e=>field('title',e.target.value)}/></label>
 <label>Publish date<input type="date" required value={draft.publishDate} onChange={e=>field('publishDate',e.target.value)}/></label><label>Short description<textarea maxLength={1500} value={draft.description} onChange={e=>field('description',e.target.value)}/></label>
 <label>Tags (up to 3, separated by commas)<input value={draft.tags.join(',')} onChange={e=>field('tags',e.target.value.split(',').slice(0,3))}/></label>
 <h3>Access to roles</h3><p>Directors always have access. Select any additional roles that may read this article.</p><div className="role-checks">{businessRoles.map(r=><label key={r}><input type="checkbox" disabled={r==='Director'} checked={r==='Director'||draft.audience.includes(r)} onChange={e=>field('audience',e.target.checked?[...draft.audience,r]:draft.audience.filter((v:string)=>v!==r))}/>{r}</label>)}</div>
 <label>Attach files<input disabled={busy} type="file" multiple accept=".html,.htm,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.csv,.mp4,.png,.jpg,.jpeg,.gif,.webp" onChange={e=>{setUploads(v=>[...v,...Array.from(e.target.files||[])]);e.target.value='';}}/></label><p>HTML and PDF files display in the article. Images and MP4 videos can be viewed here; other documents are available to download. Up to 25 MB per file (HTML: 1 MB).</p>
 {attachments.map(f=><p key={f.id}>{f.name} <button type="button" disabled={busy} onClick={()=>setAttachments(v=>v.filter(x=>x.id!==f.id))}>Remove</button></p>)}{uploads.map((f,i)=><p key={i}>{f.name} <button type="button" disabled={busy} onClick={()=>setUploads(v=>v.filter((_,n)=>n!==i))}>Remove</button></p>)}
 {board.access>=3&&<label><input type="checkbox" checked={draft.pinned} onChange={e=>field('pinned',e.target.checked)}/> Always on Top</label>}
 {error&&<p role="alert" className="danger">{error}</p>}<div><button className="primary" disabled={busy}>{busy?'Saving…':article?'Save article':'Publish article'}</button> <button type="button" disabled={busy} onClick={close}>Cancel</button></div></form>;
}
function ArticleAttachments({article}:any){const files=article.attachmentInfo||[{id:article.content,name:'Full article',type:article.contentType||'text/html'}];return <div>{files.map((f:any)=>{const url='/api/articles/'+article.id+'?file='+encodeURIComponent(f.id)+'&v='+article.version;return <section key={f.id}><h3>{f.name}</h3>{['text/html','application/pdf'].includes(f.type)?<iframe title={f.name} className="article-frame" sandbox={f.type==='text/html'?'':undefined} referrerPolicy="no-referrer" src={url}/>:f.type==='video/mp4'?<video controls preload="metadata" style={{maxWidth:'100%'}} src={url}/>:f.type?.startsWith('image/')?<img style={{maxWidth:'100%'}} alt={f.name} src={url}/>:null}<p><a href={url+'&download=1'}>Download {f.name}</a></p></section>;})}</div>;}
export function ArticleBoard({s,board,act,conversation}:any){
 const [search,setSearch]=useState(''),[tag,setTag]=useState(''),[selected,setSelected]=useState(''),[editing,setEditing]=useState<any>(null),[creating,setCreating]=useState(false),[error,setError]=useState('');
 useEffect(()=>{setSelected(new URLSearchParams(location.search).get('article')||'');setEditing(null);setCreating(false);setSearch('');setTag('');},[board.id]);
 const all=(s.articles||[]).filter((a:any)=>a.board===board.id),article=all.find((a:any)=>a.id===selected);
 const list=all.filter((a:any)=>(!tag||a.tags.includes(tag))&&[a.title,a.description,...a.tags].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a:any,b:any)=>b.publishDate.localeCompare(a.publishDate)||b.createdAt.localeCompare(a.createdAt));
 const select=(id:string)=>{setSelected(id);history.replaceState(null,'','/?board='+board.id+(id?'&article='+id:''));};
 const run=async(p:any)=>{setError('');try{await act(p);}catch(e:any){setError(e.message);}};
 if(creating||editing)return <ArticleEditor key={editing?.id||'new'} article={editing} board={board} act={act} close={()=>{setCreating(false);setEditing(null);}}/>;
 if(article)return <section className="article-reading"><button onClick={()=>select('')}>← All articles</button><h1>{article.title}</h1><p className="muted">{article.publishDate} · Published by {s.users.find((u:any)=>u.id===article.author)?.name||'Former member'}</p><p>{article.description}</p><div className="article-tags">{article.tags.map((t:string)=><span key={t}>{t}</span>)}</div><div className="toolbar">{board.access>=2&&article.author===s.me.id&&<button onClick={()=>setEditing(article)}>Edit article</button>}{board.access>=3&&<button onClick={()=>run({op:'article.pin',board:board.id,id:article.id,version:article.version,pinned:!article.pinned})}>{article.pinned?'Remove Always on Top':'Always on Top'}</button>}{(board.access>=3||board.access>=2&&article.author===s.me.id)&&<button className="danger" onClick={async()=>{if(confirm('Delete this article and hide its discussion?')){try{await act({op:'article.delete',board:board.id,id:article.id,version:article.version,confirm:true});select('');}catch{}}}}>Delete article</button>}</div>{error&&<p role="alert">{error}</p>}<ArticleAttachments article={article}/><h2>Discussion</h2>{conversation(article)}</section>;
 const cards=(items:any[])=>items.map(a=><article className="article-card" key={a.id}><div className="article-tags">{a.tags.map((t:string)=><span key={t}>{t}</span>)}</div><button className="article-title" onClick={()=>select(a.id)}>{a.title}</button><p>{a.description}</p><small>{a.publishDate} · {s.users.find((u:any)=>u.id===a.author)?.name||'Former member'}</small><button onClick={()=>select(a.id)}>Read article →</button></article>);
 return <section><div className="toolbar"><input aria-label="Search articles" placeholder="Search articles…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter by tag" value={tag} onChange={e=>setTag(e.target.value)}><option value="">All tags</option>{[...new Set(all.flatMap((a:any)=>a.tags))].sort().map((t:any)=><option key={t}>{t}</option>)}</select><span className="toolbar-spacer"/>{board.access>=2&&<button className="primary" onClick={()=>setCreating(true)}>Add article</button>}</div>{list.some((a:any)=>a.pinned)&&<><h2>Always on Top</h2><div className="article-grid">{cards(list.filter((a:any)=>a.pinned))}</div><hr className="article-divider"/></>}<div className="article-grid">{cards(list.filter((a:any)=>!a.pinned))}</div>{!list.length&&<p>No articles match this selection.</p>}</section>;
}
