'use client';
import {accessOptions,accessLabel,accessName} from '@/lib/access';
import {learningBoardId} from '@/lib/learning';
import {NoticeMembers} from './notice-members';
import {noticeBoardId,noticeCategories,noticeGroups,defaultNoticeCategory,defaultNoticeGroup,articleNoticeGroups,noticeGroupAccess,noticeArticleLevel,canPublishByRole} from '@/lib/notice-board';
import {useEffect,useState} from 'react';
import {compareArticles} from '../lib/article-order';
import {businessRoles,roleLabel,roleLabels} from '../lib/business-roles';
const call=async(path:string,data?:any)=>{const r=await fetch('/api/'+path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:undefined);if(!r.ok)throw new Error(((await r.json()) as any).error||'Request failed');return r.json() as Promise<any>;};
export function RoleChecks({value,onChange,lockDirector=false}:{value:string[];onChange:(v:string[])=>void;lockDirector?:boolean}){return <div className="role-checks">{businessRoles.map(r=><label key={r}><input type="checkbox" checked={value.includes(r)} disabled={lockDirector&&r==='Director'} onChange={e=>onChange(e.target.checked?[...value,r]:value.filter(x=>x!==r))}/>{roleLabel(r)}</label>)}</div>;}
export function BoardRoleAccess({board,act,admin=false}:any){const [grants,setGrants]=useState<Record<string,string>>(board.roleAccess||{}),[busy,setBusy]=useState(false);useEffect(()=>setGrants(board.roleAccess||{}),[board.version]);return <section><h3>Access by role</h3><p>Everyone holding a role receives its access. The strongest individual or role permission applies.</p>{businessRoles.map(r=><label className="role-grant" key={r}>{roleLabel(r)}<select value={grants[r]||''} onChange={e=>{const next={...grants};if(e.target.value)next[r]=e.target.value;else delete next[r];setGrants(next);}}><option value="" disabled={!admin&&r==='Director'&&!!board.roleAccess?.Director}>No Access</option>{accessOptions.map(v=><option key={v.value} value={v.value}>{v.label}</option>)}</select></label>)}<button className="primary" disabled={busy||board.archived} onClick={async()=>{setBusy(true);try{await act({op:'board.roles',board:board.id,version:board.version,grants});}catch{}finally{setBusy(false);}}}>Save role access</button></section>;}
function ArticleEditor({article,board,act,close,s,group,category,branch}:any){
 const learning=board.id===learningBoardId,notice=board.id===noticeBoardId,userId=s.me.id,metadataOnly=!!article&&article.author!==userId&&!s.me.admin&&(notice?noticeArticleLevel(board,s.me,article):board.access)<2.5;
 const [draft,setDraft]=useState<any>(article?{...article,category:article.category||'',noticeGroups:articleNoticeGroups(article),branch:article.branch||'',individualAccess:article.individualAccess||[],retainLegacyAccess:!!article.legacyNoticeAccess}:{category:category||(notice?defaultNoticeCategory:''),noticeGroups:[group||defaultNoticeGroup],branch:branch||'',individualAccess:[],title:'',description:'',publishDate:new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Singapore'}),tags:[],audience:'all',pinned:false});
 const [attachments,setAttachments]=useState<any[]>(article?.attachmentInfo||(article?.content?[{id:article.content,name:'Full article',type:article.contentType}]:[]));
 const [uploads,setUploads]=useState<File[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[person,setPerson]=useState('');
 const people=s.noticePeople||s.users,field=(key:string,value:any)=>setDraft({...draft,[key]:value});
 const needsBranch=notice&&(draft.noticeGroups.includes('Branch')||draft.category==='Branch');
 const level=notice?noticeArticleLevel(board,s.me,draft):board.access;
 return <form className="article-editor panel detail-body" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{
  const files=[...attachments];for(const file of uploads){const form=new FormData();form.append('board',board.id);form.append('noticeGroups',JSON.stringify(draft.noticeGroups));if(article)form.append('articleId',article.id);form.append('file',file);const response=await fetch('/api/article-content',{method:'POST',body:form});const result=await response.json() as any;if(!response.ok)throw Error(result.error||'Upload failed');files.push(result);setAttachments([...files]);setUploads(v=>v.filter(f=>f!==file));}
  const content=files.find(f=>['text/html','application/pdf'].includes(f.type))?.id||files[0]?.id;await act({op:'article.save',...draft,board:board.id,content,attachments:files.map(f=>f.id),tags:draft.tags.map((t:string)=>t.trim()).filter(Boolean)});close();
 }catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <h2>{article?'Edit article':'New article'}</h2><label>Title<input required maxLength={200} value={draft.title} onChange={e=>field('title',e.target.value)}/></label>
 {notice&&<section><h3>Publish to Notice Groups</h3><p>Select one or more groups. One article can appear in several groups.</p><div className="role-checks">{noticeGroups.map(g=><label key={g}><input type="checkbox" checked={draft.noticeGroups.includes(g)} disabled={!canPublishByRole(s.me)&&noticeGroupAccess(board,s.me,g)<2&&!(article&&articleNoticeGroups(article).includes(g))} onChange={e=>field('noticeGroups',e.target.checked?[...draft.noticeGroups,g]:draft.noticeGroups.filter((v:string)=>v!==g))}/>{g}</label>)}</div></section>}
 <label>{learning?'Learning Category':'Category'}{learning?<><input required maxLength={80} list="learning-categories" placeholder="Choose a category or type a new one" value={draft.category} onChange={e=>field('category',e.target.value)}/><datalist id="learning-categories">{[...new Set([...(board.learningCategories||[]),...(s.articles||[]).filter((a:any)=>a.board===learningBoardId).map((a:any)=>a.category).filter(Boolean)])].sort().map((c:any)=><option key={c} value={c}/>)}</datalist></>:<select required={notice} value={draft.category} onChange={e=>field('category',e.target.value)}>{!notice&&<option value="">Uncategorised</option>}{noticeCategories.map(c=><option key={c}>{c}</option>)}</select>}</label>
 {needsBranch&&<label>Branch<select required value={draft.branch} onChange={e=>field('branch',e.target.value)}><option value="">Select a branch</option>{(s.branches||[]).map((b:any)=><option key={b.id} value={b.id}>{b.name} ({b.abbreviation})</option>)}</select></label>}
 <label>Publish date<input type="date" required value={draft.publishDate} onChange={e=>field('publishDate',e.target.value)}/></label><label>Short description<textarea maxLength={1500} value={draft.description} onChange={e=>field('description',e.target.value)}/></label>
 <label>Tags (up to 3, separated by commas)<input value={draft.tags.join(',')} onChange={e=>field('tags',e.target.value.split(',').slice(0,3))}/></label>
 {!learning&&<section className="article-access"><h3>Article access</h3><p className="article-access-intro">Choose all eligible {notice?'Notice Group':'board'} members, selected roles, or individual people. Authors and administrators retain access; existing manager and Director permissions still apply.</p>
 <div className="article-access-block"><h4>Grant access to groups and roles</h4><p>{notice?"Eligible members are active users with access to at least one selected Notice Group through its Members settings, either individually or by role. This does not automatically include all staff.":"Eligible members are active users who already have access to this board, individually or through a role."}</p><label className="article-access-choice"><input type="checkbox" checked={draft.audience==='all'} onChange={e=>field('audience',e.target.checked?'all':(!s.me.admin&&Array.isArray(article?.audience)&&article.audience.includes('Director')?['Director']:[]))}/> All eligible {notice?'Notice Group':'board'} members</label>
 {draft.audience!=='all'&&<div className="article-access-roles"><h4>Grant access to roles</h4><p>Selected roles narrow access among eligible members. People without group or board access must be added individually below.</p><RoleChecks lockDirector={!s.me.admin&&!!article&&Array.isArray(article.audience)&&article.audience.includes('Director')} value={draft.audience} onChange={v=>field('audience',v)}/></div>}</div>
 <div className="article-access-block"><h4>Grant access to individuals</h4><p>Selected people can read this article and its discussion even without group or board membership. Invitees receive access after accepting their invitation.</p><div className="article-access-picker"><select aria-label="Select an individual reader" value={person} onChange={e=>setPerson(e.target.value)}><option value="">Choose a person</option>{people.filter((u:any)=>u.active&&!u.deleted&&!draft.individualAccess.includes(u.id)).map((u:any)=><option key={u.id} value={u.id}>{u.name} · {u.email}{u.onboarding?' · Awaiting acceptance':''}</option>)}</select><button type="button" disabled={!person||busy} onClick={()=>{field('individualAccess',[...draft.individualAccess,person]);setPerson('');}}>Add individual</button></div>
 {draft.individualAccess.map((id:string)=><div className="member-row" key={id}><span>{people.find((u:any)=>u.id===id)?.name||'Inactive or former user'}</span><button type="button" disabled={busy} onClick={()=>field('individualAccess',draft.individualAccess.filter((v:string)=>v!==id))}>Remove individual</button></div>)}
 </div>{article?.legacyNoticeAccess&&<label className="article-access-legacy"><input type="checkbox" checked={draft.retainLegacyAccess} onChange={e=>field('retainLegacyAccess',e.target.checked)}/> Retain this article’s previous category access restrictions. Clear this to use the selected Notice Groups and article access settings. Individual grants still apply.</label>}
 </section>}
 <label>Attach files<input disabled={busy||metadataOnly} type="file" multiple accept=".html,.htm,.pdf,.doc,.docx,.ppt,.pptx,.xls,.xlsx,.txt,.csv,.mp4,.png,.jpg,.jpeg,.gif,.webp" onChange={e=>{setUploads(v=>[...v,...Array.from(e.target.files||[])]);e.target.value='';}}/></label><p>HTML, PDF, images and MP4 videos open in a separate tab; other documents are available to download. Up to 25 MB per file (HTML: 1 MB).</p>
 {attachments.map(f=><p key={f.id}>{f.name} <button type="button" disabled={busy||metadataOnly} onClick={()=>setAttachments(v=>v.filter(x=>x.id!==f.id))}>Remove</button></p>)}{uploads.map((f,i)=><p key={i}>{f.name} <button type="button" disabled={busy} onClick={()=>setUploads(v=>v.filter((_,n)=>n!==i))}>Remove</button></p>)}
 {level>=3&&<label><input type="checkbox" checked={draft.pinned} onChange={e=>field('pinned',e.target.checked)}/> Always on Top</label>}
 {error&&<p role="alert" className="danger">{error}</p>}<div><button className="primary" disabled={busy}>{busy?'Saving…':article?'Save article':'Publish article'}</button> <button type="button" disabled={busy} onClick={close}>Cancel</button></div></form>;
}
function ArticleAttachments({article}:any){const files=article.attachmentInfo||[{id:article.content,name:'Full article',type:article.contentType||'text/html'}];return <div className="article-attachments">{files.map((f:any)=>{const url='/api/articles/'+article.id+'?file='+encodeURIComponent(f.id)+'&v='+article.version;return <div key={f.id}><strong>{f.name}</strong> <a href={url} target="_blank" rel="noopener noreferrer">Open in new tab ↗</a> <a href={url+'&download=1'}>Download</a></div>;})}</div>;}
export function ArticleBoard({s,board,act,conversation}:any){
 const learning=board.id===learningBoardId,notice=board.id===noticeBoardId;
 const [group,setGroup]=useState(defaultNoticeGroup),[category,setCategory]=useState(''),[branch,setBranch]=useState('');
 const [search,setSearch]=useState(''),[tag,setTag]=useState(''),[selected,setSelected]=useState(''),[editing,setEditing]=useState<any>(null),[creating,setCreating]=useState(false),[removing,setRemoving]=useState(''),[error,setError]=useState('');
 useEffect(()=>{const params=new URLSearchParams(location.search),linked=(s.articles||[]).find((a:any)=>a.id===params.get('article')),requested=params.get('noticeGroup');setSelected(params.get('article')||'');setEditing(null);setCreating(false);setSearch('');setTag('');setCategory(params.get('category')||'');setGroup(requested&&noticeGroups.includes(requested)?requested:linked?articleNoticeGroups(linked)[0]:defaultNoticeGroup);setBranch(linked?.branch||params.get('branch')||'');},[board.id]);
 const all=(s.articles||[]).filter((a:any)=>a.board===board.id&&!a.deleted),article=all.find((a:any)=>a.id===selected);
 const scoped=notice?all.filter((a:any)=>articleNoticeGroups(a).includes(group)&&(group!=='Branch'||!!branch&&a.branch===branch)):all;
 const level=(a?:any)=>notice?(a?noticeArticleLevel(board,s.me,a):noticeGroupAccess(board,s.me,group)):board.access;
 const canEdit=(a:any)=>a.author===s.me.id||level(a)>=2.5,canDelete=(a:any)=>s.me.admin||a.author===s.me.id||level(a)>=2.5;
 const list=scoped.filter((a:any)=>(!category||a.category===category)&&(!tag||a.tags.includes(tag))&&[a.title,a.description,...a.tags].join(' ').toLowerCase().includes(search.toLowerCase())).sort(compareArticles);
 const discussionCounts:Record<string,number>={};for(const m of s.messages||[])if(!m.removed)discussionCounts[m.subject]=(discussionCounts[m.subject]||0)+1;
 const route=(id='',g=group,b=branch,c=category)=>'/?board='+board.id+(notice?'&noticeGroup='+encodeURIComponent(g):'')+(b?'&branch='+encodeURIComponent(b):'')+(c?'&category='+encodeURIComponent(c):'')+(id?'&article='+id:'');
 const select=(id:string)=>{setSelected(id);history.replaceState(null,'',route(id));};
 const switchGroup=(next:string)=>{setGroup(next);setBranch('');setTag('');setSelected('');setSearch('');history.replaceState(null,'',route('',next,''));};
 const groupMenu=notice?<><h2>Notice Group</h2><nav className="planning-tabs" aria-label="Notice Groups">{noticeGroups.map(g=><button key={g} aria-pressed={group===g} onClick={()=>switchGroup(g)}>{g}</button>)}</nav>{group==='Branch'&&<label>Branch<select aria-label="Filter by branch" value={branch} onChange={e=>{setBranch(e.target.value);setTag('');setSelected('');history.replaceState(null,'',route('',group,e.target.value));}}><option value="">Select a branch</option>{(s.branches||[]).map((b:any)=><option key={b.id} value={b.id}>{b.name} ({b.abbreviation})</option>)}</select>{!(s.branches||[]).length&&<p>Add branches in Administration to use this Notice Group.</p>}</label>}<NoticeMembers s={s} board={board} group={group} act={act}/></>:null;
 const run=async(p:any)=>{setError('');try{await act(p);}catch(e:any){setError(e.message);}};
 const remove=async(a:any)=>{if(!canDelete(a)||removing||!window.confirm('Remove “'+a.title+'”? The article and its discussion will no longer be visible.'))return;setRemoving(a.id);setError('');try{await act({op:'article.delete',board:board.id,id:a.id,version:a.version,confirm:true});if(selected===a.id)select('');}catch(e:any){setError(e.message||'Unable to remove article.');}finally{setRemoving('');}};
 const metadata=(a:any)=><p className="muted">Category: {a.category||'Uncategorised'}{notice?' · Notice Groups: '+articleNoticeGroups(a).join(', '):''}{a.branch?' · '+((s.branches||[]).find((b:any)=>b.id===a.branch)?.name||'Branch unavailable'):''}</p>;
 if(creating||editing)return <ArticleEditor key={editing?.id||'new'} article={editing} s={s} group={group} category={category} branch={branch} board={board} act={act} close={()=>{setCreating(false);setEditing(null);}}/>;
 if(article)return <section className="article-reading">{groupMenu}<div className="toolbar"><button onClick={()=>select('')}>← All articles</button><a href={'/api/articles/'+article.id+'?v='+article.version}>← Return to main article</a></div><h1>{article.title}</h1>{metadata(article)}<p className="muted">{article.publishDate} · Published by {s.users.find((u:any)=>u.id===article.author)?.name||'Former member'}</p><p>{article.description}</p><div className="article-tags">{article.tags.map((t:string)=><span key={t}>{t}</span>)}</div><div className="toolbar">{canEdit(article)&&<button onClick={()=>setEditing(article)}>Edit details</button>}{level(article)>=3&&<button onClick={()=>run({op:'article.pin',board:board.id,id:article.id,version:article.version,pinned:!article.pinned})}>{article.pinned?'Remove Always on Top':'Always on Top'}</button>}{canDelete(article)&&<button className="danger" disabled={!!removing} onClick={()=>remove(article)}>{removing===article.id?'Removing…':'Remove article'}</button>}</div>{error&&<p role="alert">{error}</p>}<ArticleAttachments article={article}/><h2>Discussion</h2>{conversation(article)}</section>;
 const cards=(items:any[])=>items.map((a,i)=><article className="article-list-row" key={a.id}><div className="article-list-copy"><div className="article-title-line"><a className="article-title" href={'/api/articles/'+a.id+'?v='+a.version} target="_blank" rel="noopener noreferrer">{a.title} ↗</a><span className="article-category" title={a.category||'Uncategorised'}>{a.category||'Uncategorised'}</span></div><p className="article-summary" title={a.description}>{a.description||'—'}</p><div className="article-list-meta"><small>{a.publishDate} · {s.users.find((u:any)=>u.id===a.author)?.name||'Former member'}</small><div className="article-tags">{a.tags.map((t:string)=><span key={t}>{t}</span>)}</div></div></div><div className="article-list-actions"><a href={'/api/articles/'+a.id+'?v='+a.version} target="_blank" rel="noopener noreferrer">Read article ↗</a><button onClick={()=>select(a.id)}>Discussions & Details{discussionCounts[a.id]>0&&<span> · {discussionCounts[a.id]} {discussionCounts[a.id]===1?'message':'messages'}</span>}</button><div className="article-edit-actions">{canEdit(a)&&<button onClick={()=>setEditing(a)}>Edit details</button>}{canDelete(a)&&<button className="danger" disabled={!!removing} aria-label={'Remove article: '+a.title} onClick={()=>remove(a)}>{removing===a.id?'Removing…':'Remove'}</button>}{level()>=3&&<div><button disabled={!!search||!!tag||!!category||i===0} aria-label={'Move '+a.title+' up'} onClick={()=>run({op:'article.move',board:board.id,id:a.id,version:a.version,group,branch:notice&&group==='Branch'?branch:undefined,direction:'up'})}>↑</button> <button disabled={!!search||!!tag||!!category||i===items.length-1} aria-label={'Move '+a.title+' down'} onClick={()=>run({op:'article.move',board:board.id,id:a.id,version:a.version,group,branch:notice&&group==='Branch'?branch:undefined,direction:'down'})}>↓</button></div>}</div></div></article>);
 return <section>{learning&&<p className="muted">Share learning with all staff. Everyone can create a post and edit or delete their own; administrators can manage all posts.</p>}{groupMenu}<div className="toolbar"><input aria-label="Search articles" placeholder="Search articles…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Filter by category" value={category} onChange={e=>{setCategory(e.target.value);history.replaceState(null,'',route('',group,branch,e.target.value));}}><option value="">All categories</option>{(learning?[...new Set([...(board.learningCategories||[]),...all.map((a:any)=>a.category).filter(Boolean)])].sort():noticeCategories).map((c:any)=><option key={c}>{c}</option>)}</select><select aria-label="Filter by tag" value={tag} onChange={e=>setTag(e.target.value)}><option value="">All tags</option>{[...new Set(scoped.flatMap((a:any)=>a.tags))].sort().map((t:any)=><option key={t}>{t}</option>)}</select><span className="toolbar-spacer"/>{(canPublishByRole(s.me)||level()>=2)&&(!notice||group!=='Branch'||!!branch)&&<button className="primary" onClick={()=>setCreating(true)}>Add article</button>}</div><p className="muted">New articles appear first. Articles marked Always on Top remain pinned above the list.</p>{error&&<p role="alert" className="danger">{error}</p>}{level()>=3&&(search||tag||category)&&<p>Clear filters to rearrange articles.</p>}{list.some((a:any)=>a.pinned)&&<><h2>Always on Top</h2><div className="article-list">{cards(list.filter((a:any)=>a.pinned))}</div><hr className="article-divider"/></>}<div className="article-list">{cards(list.filter((a:any)=>!a.pinned))}</div>{!list.length&&<p>{notice&&group==='Branch'&&!branch?'Select a branch to view articles.':'No articles match this selection or your access permissions.'}</p>}</section>;
}
