'use client';
import {Price,products} from '@/lib/planning';
import {Num,money} from './planning-controls';
const descriptions:Record<string,string>={A:'Academic coaching · 2-hour lessons · typically 6 or fewer students',B:'Physical tutorial · 1.5-hour lessons · up to 12 students',C:'Online live tutorials · prices per class',D:'E-learning · annual package prices'};
export function PlanningPrices({prices,editable,onChange}: {prices:Price[];editable:boolean;onChange:(id:string,value:number|null)=>void}){
 return <><nav className="planning-product-nav" aria-label="Price list products">{products.map(p=><a key={p} href={`#price-product-${p}`}><strong>Product {p}</strong><small>{descriptions[p]}</small></a>)}</nav><p>2027 prices · SGD. Package totals, savings and changes from 2026 appear above each lesson price. Savings use the final rounded prices.</p>
 {products.map(product=>{const selected=prices.filter(p=>p.product===product),groups=[...new Set(selected.map(p=>p.group))];return <section key={product} id={`price-product-${product}`} className="planning-product-section"><h2>Product {product} · 2027</h2><p>{descriptions[product]}</p>
 {product==='A'&&<p>One-time registration: $80. Package totals below use 12 lessons per subject (Terms 1 & 3); Terms 2 & 4 have 14 lessons. The 3+ subjects total covers 36 lessons (3 subjects × 12 lessons). Siblings may pool 3 or more subjects.</p>}
 {product==='B'&&<p>Lite: 4 lessons. Package totals below use 12 lessons per subject. The 3+ subjects total covers 36 lessons (3 subjects × 12 lessons). Siblings may pool 3 or more subjects. The workbook does not provide 2026 Product B prices.</p>}
 {groups.map(group=>{const rows=selected.filter(p=>p.group===group),levels=[...new Set(rows.map(p=>p.level))],columns=rows.filter(p=>p.level===levels[0]);return <section className="planning-price-section" key={group}><header><h3>{group}</h3><p>{product==='D'?'Annual package · total price for the selected number of subjects':'Compare packages · totals and savings shown in every column'}</p></header><div className="planning-scroll"><table className="planning-price-matrix"><thead><tr><th>Level</th>{columns.map(p=><th key={p.id}>{p.category}<small>{product==='D'?'S$ / year':'S$ / '+p.unit}</small></th>)}</tr></thead><tbody>{levels.map(level=><tr key={level}><th>{level}</th>{rows.filter(p=>p.level===level).map(p=>{const standard=rows.find(x=>x.level===level&&x.tier===0)?.amount;const discount=p.amount===null||!standard?null:100*(1-p.amount/(standard*(product==='D'?(p.tier!+1):1)));const units=['A','B'].includes(product)&&p.tier===3?36:p.units||1;const change=p.amount===null||!p.previous?null:(p.amount/p.previous-1)*100;return <td key={p.id} className={p.tier===3?'planning-price-gold':p.tier===2?'planning-price-green':''}>{p.unavailable?<span className="planning-price-unavailable">Unavailable</span>:<><div className="planning-price-meta"><small>{product==='D'?'Annual total':`${money(p.amount===null?null:p.amount*units)} total · ${units} ${product==='C'?(units===1?'class':'classes'):(units===1?'lesson':'lessons')}`}</small><small>{p.tier?discount===null?'Savings pending':`${discount.toFixed(1)}% off${product==='D'?' per subject':''}`:'Standard rate · 0% off'}</small><small>{p.previous===null||p.previous===undefined||p.amount===null?'2026 comparison unavailable':`${p.amount>p.previous?'+':''}${money(p.amount-p.previous)} vs 2026${change===null?'':` (${change>0?'+':''}${change.toFixed(1)}%)`}`}</small><small>{p.previous===null||p.previous===undefined?'':'2026 price: '+money(p.previous)}</small></div><div className="planning-lesson-price">{editable?<Num label={`${product} ${group} ${level} ${p.category}`} value={p.amount} money step="0.01" onChange={(v:number|null)=>onChange(p.id,v)}/>:<strong>{money(p.amount)}</strong>}</div><small>{product==='D'?'per year':`per ${p.unit}`}</small></>}</td>;})}</tr>)}</tbody></table></div></section>;})}
 {product==='C'&&<p>Package totals calculate from the displayed per-class rates and retain cents.</p>}{product==='D'&&<p>Pre-school 2027 pricing is pending. Aspire Hub student prices are final package prices; discounts do not stack. Each available package shows its change from the corresponding 2026 package.</p>}</section>;})}
 <details><summary>Price source</summary><p>2027 prices come from the supplied 22 September workbook. The layout follows the supplied Aspire Hub price list. Comparisons use the corresponding 2026 prices where provided; missing values remain unavailable. GST treatment is not specified in the source.</p></details></>;
}
