'use client';
import {useState} from 'react';
import {Price,products} from '@/lib/planning';
import {Num,money} from './planning-controls';
const descriptions:Record<string,string>={A:'Academic coaching · 2-hour lessons · typically 6 or fewer students',B:'Physical tutorial · 1.5-hour lessons · up to 12 students',C:'Online live tutorials · prices per class',D:'E-learning · annual package prices'};
export function PlanningPrices({prices,editable,onChange}: {prices:Price[];editable:boolean;onChange:(id:string,value:number|null)=>void}){
 const [product,setProduct]=useState('A'),[totals,setTotals]=useState(false);
 const selected=prices.filter(p=>p.product===product),groups=[...new Set(selected.map(p=>p.group))];
 return <><div className="planning-product-nav">{products.map(p=><button key={p} aria-pressed={product===p} onClick={()=>setProduct(p)}><strong>Product {p}</strong><small>{descriptions[p]}</small></button>)}</div><div className="planning-toolbar"><h2>Product {product} · 2027</h2>{product!=='D'&&<button aria-pressed={totals} onClick={()=>setTotals(!totals)}>{totals?'Show per-lesson prices':'Show package totals'}</button>}</div><p>{descriptions[product]}. All prices in SGD.</p>{product==='A'&&<p>One-time registration: $80. Academic packages: 12 lessons in Terms 1 & 3, 14 in Terms 2 & 4. Siblings may pool 3 or more subjects.</p>}{product==='B'&&<p>Lite: 4 lessons. Academic packages: 12 or more lessons. Siblings may pool 3 or more subjects.</p>}
 {groups.map(group=>{const rows=selected.filter(p=>p.group===group),levels=[...new Set(rows.map(p=>p.level))],columns=rows.filter(p=>p.level===levels[0]);return <section className="planning-price-section" key={group}><h3>{group}</h3><div className="planning-scroll"><table><thead><tr><th>Level</th>{columns.map(p=><th key={p.id}>{p.category}<small>{product==='D'?'S$ / year':totals?`${p.units} ${product==='C'?'classes':'lessons'}`:'S$ / '+p.unit}</small></th>)}</tr></thead><tbody>{levels.map(level=><tr key={level}><th>{level}</th>{rows.filter(p=>p.level===level).map(p=>{const standard=rows.find(x=>x.level===level&&x.tier===0)?.amount;const discount=p.amount===null||!standard?null:100*(1-p.amount/(standard*(product==='D'?(p.tier!+1):1)));return <td key={p.id} className={p.tier?'planning-discount':''}>{p.unavailable?<span>Unavailable</span>:editable&&!totals?<Num label={`${product} ${group} ${level} ${p.category}`} value={p.amount} money step="0.01" onChange={(v:number|null)=>onChange(p.id,v)}/>:money(p.amount===null?null:p.amount*(totals&&product!=='D'?p.units||1:1))}{!!p.tier&&!p.unavailable&&discount!==null&&<small>{discount.toFixed(1)}% saving{product==='D'?' per subject':''}</small>}</td>;})}</tr>)}</tbody></table></div></section>;})}
 {product==='D'&&<p>Pre-school 2027 pricing is pending. Aspire Hub student prices above are final package prices; discounts do not stack.</p>}{totals&&product!=='D'&&<p>Totals calculate from the displayed per-lesson rates. The workbook rounds some Product C package totals to whole dollars; this view retains cents.</p>}
 <details><summary>Price source and comparison</summary><p>2027 prices from the supplied 22 September workbook. Savings are calculated from the final rounded prices. GST treatment is not specified in the source.</p><div className="planning-scroll"><table><thead><tr><th>Level / package</th><th>2026</th><th>2027</th><th>Change</th></tr></thead><tbody>{selected.filter(p=>p.previous!==null&&p.previous!==undefined&&!p.unavailable).map(p=><tr key={p.id}><th>{p.level}<small>{p.group} · {p.category}</small></th><td>{money(p.previous!)}</td><td>{money(p.amount)}</td><td>{p.amount===null||!p.previous?'Pending':((p.amount/p.previous-1)*100).toFixed(1)+'%'}</td></tr>)}</tbody></table></div>{product==='B'&&<p>The workbook does not give 2026 Product B prices.</p>}</details></>;
}
