'use client';
import {Price,products} from '@/lib/planning';
import {priceFigures,priceOrder} from '@/lib/price-calculations';
import {Num,money} from './planning-controls';
const descriptions:Record<string,string>={A:'Academic coaching · 2-hour lessons',B:'Physical tutorial · 1.5-hour lessons',C:'Online live tutorials · prices per class',D:'E-learning · annual package prices'};
export function PlanningPrices({prices,editable,onChange}:{prices:Price[];editable:boolean;onChange:(id:string,value:number|null,field?:'amount'|'discount')=>void}){
 return <><nav className="planning-product-nav" aria-label="Price list products">{products.map(p=><a key={p} href={'#price-product-'+p}><strong>Product {p}</strong><small>{descriptions[p]}</small></a>)}</nav><p>All prices in SGD. Large figures show total fee / per-lesson fee. Savings compare with the standard rate for the same lesson count.</p>
 {products.map(product=>{const selected=priceOrder(prices.filter(p=>p.product===product)),groups=[...new Set(selected.map(p=>p.group))];return <section key={product} id={'price-product-'+product} className="planning-product-section"><h2>Product {product} · 2027</h2><p>{descriptions[product]}</p>{['A','B'].includes(product)&&<p>Standard: 1 lesson · Lite: 8 lessons · Package: 12 lessons · 3+ subjects: 36 lessons (3 × 12). {product==='A'?'Registration: $80. Terms 2 & 4 have 14 lessons per subject; totals below use 12.':''}</p>}
 {groups.map(group=>{const rows=selected.filter(p=>p.group===group),levels=[...new Set(rows.map(p=>p.level))],columns=rows.filter(p=>p.level===levels[0]);return <section className="planning-price-section" key={group}><h3>{group}</h3><div className="planning-scroll"><table className="planning-price-matrix"><thead><tr><th>Level</th>{columns.map(p=><th key={p.id}>{p.category}<small>{product==='D'?'Annual fee':'Total fee / '+(product==='C'?'per-class fee':'per-lesson fee')}</small></th>)}</tr></thead><tbody>{levels.map(level=><tr key={level}><th>{level}</th>{rows.filter(p=>p.level===level).map(p=>{const standard=rows.find(x=>x.level===level&&x.tier===0),f=priceFigures(p,standard),isAnnual=product==='D';const annualDiscount=standard?.amount==null||p.amount===null?null:standard.amount*((p.tier??0)+1)-p.amount;const discountPercent=isAnnual?(standard?.amount&&annualDiscount!==null?annualDiscount/(standard.amount*((p.tier??0)+1))*100:null):f.percent;return <td key={p.id} className={p.tier===3?'planning-price-gold':p.tier===2?'planning-price-green':''}>{p.unavailable?<span>Unavailable</span>:<><strong className="price-fee-pair">{isAnnual?money(p.amount):money(f.total)+' / '+money(p.amount)}</strong><small className="price-discount-line">{isAnnual?money(annualDiscount)+' total discount':money(f.totalDiscount)+' / '+money(f.discount)} / {discountPercent===null?'Pending':discountPercent.toFixed(1)+'% off'}</small><small className="price-history-line">2026: {p.previous==null?'Unavailable':isAnnual?money(p.previous):money(f.previousTotal)+' / '+money(p.previous)}</small>{editable&&<div className="price-edit-fields">{['A','B'].includes(product)&&!!p.tier&&p.discount!==undefined?<label>Discount per lesson<Num label={`${product} ${level} ${p.category} discount`} value={p.discount} money step="0.01" onChange={(v:number|null)=>onChange(p.id,v,'discount')}/></label>:<label>{isAnnual?'Annual fee':p.tier?'Fee per lesson':'Standard fee per lesson'}<Num label={`${product} ${level} ${p.category} fee`} value={p.amount} money step="0.01" onChange={(v:number|null)=>onChange(p.id,v,'amount')}/></label>}</div>}</>}</td>;})}</tr>)}</tbody></table></div></section>;})}</section>;})}
 <p className="muted">Discount line: total discount / discount per lesson / percentage off. The 2026 total uses the same lesson count for a like-for-like comparison. Product B’s 2026 prices were not supplied. Product D remains an annual package.</p></>;
}
