'use client';
import {annual,Budget,calculate,clone,months,Rules} from '@/lib/planning';
import {budgetCashflow,cashflowSource} from '@/lib/budget-cashflow';
import {money,Num} from './planning-controls';
export function PlanningCashflow({budget:b,rules,year,editable,onChange}:{budget:Budget;rules:Rules;year:number;editable:boolean;onChange:(b:Budget)=>void}){
 const flow=budgetCashflow(b,rules),shares=cashflowSource.shares;
 const series=[{name:'Cash receipts',values:flow.receipts,color:'#176e6b'},{name:'Cash payments',values:flow.payments,color:'#b1862d'},{name:'Closing cash',values:flow.closing,color:'#635497'}].filter(s=>s.values.every(v=>v!==null));
 const chartValues=series.flatMap(s=>s.values as number[]),min=Math.min(0,...chartValues),max=Math.max(100,...chartValues),height=max-min;
 const x=(i:number)=>70+i*64,y=(v:number)=>220-(v-min)/height*185;
 const change=(fn:(c:NonNullable<Budget['cashflow']>)=>void)=>{const n=clone(b);n.cashflow??={annualTarget:null,openingCash:null,payments:Array(12).fill(null)};fn(n.cashflow);onChange(n);};
 const rows=[{name:'Collections from customers',values:flow.collections},{name:'Other income received',values:flow.other},{name:'Total cash receipts',values:flow.receipts,total:true},{name:'Cash payments',values:flow.payments},{name:'Net cashflow',values:flow.net,total:true},{name:'Opening cash balance',values:flow.opening,balance:true},{name:'Closing cash balance',values:flow.closing,balance:true,total:true}];
 return <section id="online-cashflow"><h3>7. Monthly cashflow projection · {year}</h3><p>Customer collections = annual collection target × each month’s share of 2025 collections in the 88Tuition workbook. The percentages determine receipt timing; the P&L revenue schedule stays unchanged.</p>
  <fieldset disabled={!editable}><div className="planning-fields"><label>Annual collection target override (S$)<Num label="Annual cash collection target" placeholder="Use budget revenue" money value={b.cashflow?.annualTarget??null} step="100" onChange={(v:number|null)=>change(c=>c.annualTarget=v)}/><small>Blank uses this budget’s annual revenue: {money(annual(calculate(b,rules).revenue))}. A zero target is allowed.</small></label><label>Opening cash on 1 January (S$)<Num label="Opening cash balance" min={-1e12} money value={b.cashflow?.openingCash??null} step="100" onChange={(v:number|null)=>change(c=>c.openingCash=v)}/><small>Enter 0 if starting without cash. Blank keeps cash balances pending.</small></label></div></fieldset>
  <div className="planning-kpis"><div><small>Annual cash receipts</small><strong>{money(annual(flow.receipts))}</strong></div><div><small>Annual cash payments</small><strong>{money(annual(flow.payments))}</strong></div><div><small>Net cashflow</small><strong>{money(annual(flow.net))}</strong></div><div><small>Closing cash · December</small><strong>{money(flow.closing[11])}</strong></div></div>
  <p>Payments initially follow the monthly direct costs, operating costs and taxes in this budget. Other income is received in its budgeted month. Change the monthly cash payments below where payment timing differs. Opening receivables/payables and financing are not supplied by the workbook.</p>
  {series.length>0&&<figure className="online-cash-chart"><figcaption>Monthly cash receipts, payments and closing balance</figcaption><svg viewBox="0 0 820 270" role="img" aria-label="Monthly cashflow chart. Exact amounts are in the table below."><line x1="70" y1={y(0)} x2="774" y2={y(0)} stroke="#c5d4ce"/>{[min,(min+max)/2,max].map((v,i)=><text key={i} x="62" y={y(v)+4} textAnchor="end" fontSize="11" fill="#526c63">{(v/100000).toFixed(1)}k</text>)}{series.map(s=><polyline key={s.name} points={s.values.map((v,i)=>`${x(i)},${y(v!)}`).join(' ')} fill="none" stroke={s.color} strokeWidth="3"/>)}{months.map((m,i)=><text key={m} x={x(i)} y="250" textAnchor="middle" fontSize="12" fill="#526c63">{m}</text>)}<text x="70" y="16" fontSize="11" fill="#526c63">S$ thousands</text></svg><div>{series.map(s=><span key={s.name} style={{color:s.color}}>{s.name}</span>)}</div></figure>}
  <div className="planning-scroll"><table><thead><tr><th>Cashflow line</th>{months.map(m=><th key={m}>{m}</th>)}<th>Year</th></tr></thead><tbody><tr><th>Collection share · 2025 pattern</th>{shares.map((v,i)=><td key={i}>{(v*100).toFixed(2)}%</td>)}<td>100.00%</td></tr>{rows.map(row=><tr className={row.total?'planning-total':''} key={row.name}><th>{row.name}</th>{row.values.map((v,i)=><td key={i} className={v!==null&&v<0?'online-negative':''}>{money(v)}</td>)}<td>{money(row.balance?(row.name==='Opening cash balance'?flow.opening[0]:flow.closing[11]):annual(row.values))}</td></tr>)}</tbody></table></div>
  <details className="planning-line"><summary>Cash payment timing — monthly overrides</summary><p>Blank uses that month’s budgeted expense. Enter the total cash payment for a month to override it; 0 means no cash paid. Include any opening payables you expect to settle.</p><fieldset disabled={!editable}><div className="planning-months">{months.map((m,i)=><label key={m}>{m}<Num label={m+' cash payments override'} placeholder="Use budget expense" value={b.cashflow?.payments[i]??null} money step="100" onChange={(v:number|null)=>change(c=>c.payments[i]=v)}/><small>Budget expense: {money(flow.expense[i])}</small></label>)}</div></fieldset></details>
  <p><strong>Closing cash = opening cash + receipts − payments.</strong> A negative balance shows a funding gap under these assumptions.</p><small>Source: {cashflowSource.file}, “{cashflowSource.sheet}” {cashflowSource.shareRange}. Only 2025 covers all 12 months. The source currency is unspecified; only the percentage pattern is used here with the budget’s S$ amounts. Monthly cents are allocated so collections reconcile exactly to the annual target.</small>
 </section>;
}
