'use client';
import {useState} from 'react';
import {Rules,products,channels,recipients,earnings} from '@/lib/planning';
import {Num,Pick,money} from './planning-controls';
export function PlanningCommissions({rules,editable,onChange,priceLabel='published prices'}:{rules:Rules;editable:boolean;onChange:(fn:(d:any)=>void)=>void;priceLabel?:string}){
 const [stage,setStage]=useState('initial'),[commission,setCommission]=useState('Physical Centre'),[students,setStudents]=useState<number|null>(1),[count,setCount]=useState<number|null>(12);
 return <>
 <div className="planning-toolbar"><h2>Commission allocation</h2><Pick label="Sale type" value={stage} onChange={setStage} options={['initial','renewal','upsell']}/></div>
 <fieldset disabled={!editable}>{channels.map(c=><section key={c}><h3>{c==='Online'?'Aspire Online':c}</h3><div className="planning-scroll"><table><thead><tr><th>Product</th>{recipients.map(r=><th key={r}>{r} %</th>)}<th>Total %</th></tr></thead><tbody>{Object.keys(rules.rates[stage][c]).map(p=>{const rates=rules.rates[stage][c][p];return <tr key={p}><th>Product {p}</th>{rates.map((v,i)=><td key={i}><Num label={`${c} ${p} ${recipients[i]}`} value={v} max={100} step={1} onChange={(v:number|null)=>onChange(d=>d.payload.rates[stage][c][p][i]=v)}/></td>)}<td>{rates.some(v=>v===null)?'Pending':rates.reduce<number>((a,b)=>a+b!,0)+'%'}</td></tr>;})}</tbody></table></div></section>)}</fieldset>
 <h2>Who earns what</h2><div className="planning-fields commission-selectors"><label className="commission-choice">Commission set<Pick value={commission} onChange={setCommission} options={channels.map(id=>({id,name:id==='Online'?'Aspire Online':id}))}/></label><label className="commission-choice">Teacher Share (%)<Num disabled={!editable} label="Teacher Share (%)" value={rules.teacher.C} max={100} onChange={(v:number|null)=>onChange(d=>{d.payload.teacher.B=v;d.payload.teacher.C=v;})}/></label><label className="commission-choice">Students<Num disabled={!editable} min={1} value={students} onChange={setStudents}/></label><label className="commission-choice">Lessons / class<Num disabled={!editable} min={1} value={count} onChange={setCount}/></label></div><p>Teacher share applies to B and C; A and D have no teacher deduction. Commissions use the full fee. A minimum of 6 students in the class is required for the 40% teacher share; for fewer than 6, teachers are paid the minimum agreed with the centre. The student count below is a calculation scenario; minimum pay is not included.</p><p>Uses {priceLabel}: A/B package rate, C 12-class rate, D one subject-year per student. Sale type: {stage}. Default: 1 student and 12 lessons. Each recipient’s commission is rounded to the nearest dollar; retained earnings use these rounded payments.</p>
 {!rules.prices.length&&<p className="warning">Prices have not been published yet. An administrator must publish the price list to calculate earnings.</p>}
 {products.flatMap(p=>(p==='C'?['C only','Existing package student']:[null]).map(group=><section key={p+(group||'')}><h3>Product {p}{group?' · '+(group==='C only'?'Enrol C only':group):''}</h3>{commission==='Online'&&!['A','B'].includes(p)?<p>Aspire Online commission applies to Products A and B only.</p>:<div className="planning-scroll"><table><thead><tr><th>Level / category</th><th>Fee</th><th>Teacher</th>{recipients.map(r=><th key={r}>{r}</th>)}<th>Retain</th><th>Retain %</th></tr></thead><tbody>{rules.prices.filter(x=>x.product===p&&(!group||x.group===group)&&x.tier===(p==='D'?0:2)).map(price=>{const fee=price.amount===null||students===null||(p!=='D'&&count===null)?null:Math.round(price.amount*students*(p==='D'?1:count!));const v=earnings(fee,['A','D'].includes(p)?0:rules.teacher[p],rules.rates[stage][commission][p],'gross');return <tr key={price.id}><th>{price.level}<small>{price.group==='C only'?'Enrol C only':price.group}</small></th><td>{money(fee)}</td><td>{money(v.teacher)}</td>{v.commissions.map((x,i)=><td key={i}>{money(x)}</td>)}<td className={v.retained!==null&&v.retained<0?'danger':''}>{money(v.retained)}</td><td>{v.percent===null?'N/A':v.percent.toFixed(1)+'%'}</td></tr>;})}</tbody></table></div>}</section>))}</>;
}
