'use client';
import {annual,Budget,clone,Line,rateFor,Rules} from '@/lib/planning';
import {BudgetDriver,deriveLine,materializeBudget} from '@/lib/budget-drivers';
import {wholeMoney as money,Num} from './planning-controls';
const percent=(v:number|null)=>v===null?'Pending':v.toLocaleString('en-SG',{maximumFractionDigits:3})+'%';
export function PlanningBudgetAssumptions({budget:b,rules,share,editable,onChange}:{budget:Budget;rules:Rules;share:number;editable:boolean;onChange:(b:Budget)=>void}){
 const change=(id:string,key:string,value:number|null)=>{const n=clone(b),l=n.lines.find(l=>l.id===id)!;if(l.driver)Object.assign(l.driver,{[key]:value});else l.rate=value;onChange(materializeBudget(n));};
 const attach=(l:Line,driver:BudgetDriver)=>{const n=clone(b);n.lines.find(x=>x.id===l.id)!.driver=driver;onChange(materializeBudget(n));};
 return <fieldset disabled={!editable} className="online-driver-grid">{b.lines.filter(l=>l.id!=='director'&&(l.driver||['teachers','cc','dc','ah'].includes(l.id))).map(l=>{
 const d=l.driver,effective=deriveLine(l);
 return <div className="online-driver" key={l.id}><h4>{l.name}</h4>
  {d?.kind==='referral'?<><div className="planning-fields"><label>Sales referred (%)<Num label={l.name+' referred percentage'} value={d.referred} max={100} step="1" onChange={(v:number|null)=>change(l.id,'referred',v)}/></label><label>Commission on referred sales (%)<Num label={l.name+' commission rate'} value={d.commission} max={100} step="1" onChange={(v:number|null)=>change(l.id,'commission',v)}/></label></div><output>Effective rate: {percent(d.referred)} × {percent(d.commission)} = <strong>{percent(effective.rate)}</strong></output><small>Applies to all revenue in {b.lines.find(x=>x.id===l.baseId)?.name||'the base line'}.</small></>:
   d?.kind==='ah-access'?<><div className="planning-fields"><label>Eligible account-terms<Num value={d.accounts} label="Eligible AH account-terms" onChange={(v:number|null)=>change(l.id,'accounts',v)}/></label><label>Fee per account-term (S$)<Num value={d.fee} money label="AH fee per account-term" step="1" onChange={(v:number|null)=>change(l.id,'fee',v)}/></label><label>Multiplier<Num value={d.multiplier} label="AH account multiplier" step="0.1" onChange={(v:number|null)=>change(l.id,'multiplier',v)}/></label></div><output>{d.accounts??'Pending'} × {money(d.fee)} × {d.multiplier??'Pending'} = <strong>{money(annual(effective.values))}/year</strong></output><small>Annual amount reconciles to the inputs. AH fees are collected monthly, one month later. The original base is 2,833 account-terms × S$12 × 3.</small></>:
   d?.kind==='employer-cpf'?<><div className="planning-fields"><label>Monthly fee before CPF (S$)<Num value={d.base} money label="Director fee before CPF" step="100" onChange={(v:number|null)=>change(l.id,'base',v)}/></label><label>Employer CPF (%)<Num value={d.cpf} max={100} label="Director employer CPF rate" step="0.1" onChange={(v:number|null)=>change(l.id,'cpf',v)}/></label></div><output>{money(d.base)} + {percent(d.cpf)} CPF = <strong>{money(effective.values[0])}/month</strong></output><small>Monthly fee × 12 = {money(annual(effective.values))}/year. CPF is the scenario’s assumption.</small></>:
   l.method==='percent'?<><div className="planning-fields"><label>{l.id==='teachers'?'Teacher share (%)':'Effective rate (%)'}<Num label={l.name+' effective rate'} value={rateFor(l,rules)} disabled={(l.rateSource||'custom')!=='custom'} max={100} step="0.1" onChange={(v:number|null)=>change(l.id,'rate',v)}/></label></div>{l.id==='teachers'&&l.baseId==='c'&&<output>Across external sales: {percent(share*100)} Product C × {percent(rateFor(l,rules))} teacher share = <strong>{percent(rateFor(l,rules)===null?null:share*rateFor(l,rules)! )}</strong></output>}{['cc','dc'].includes(l.id)&&(l.rateSource||'custom')==='custom'&&<><p>This saved effective rate has no recorded referral breakdown. Enter both inputs to replace it.</p><button onClick={()=>attach(l,{kind:'referral',referred:null,commission:null})}>Define referral assumptions</button></>}{(l.rateSource||'custom')!=='custom'&&<small>Calculated from this budget’s saved {l.rateSource} settings.</small>}</>:
   <><output>Annual amount: <strong>{money(annual(l.values))}</strong></output><p>The saved monthly amounts are retained. No supporting factors were recorded for this edited line.</p>{l.method==='manual'&&<button onClick={()=>attach(l,l.id==='ah'?{kind:'ah-access',accounts:null,fee:null,multiplier:null}:{kind:'employer-cpf',base:null,cpf:null})}>Define calculation assumptions</button>}</>}
 </div>;
 })}</fieldset>;
}
