'use client';
import {annual,Budget,calculate,clone,months,Rules} from '@/lib/planning';
import {onlineCashflow,onlinePeriods,cashflowSource} from '@/lib/budget-cashflow';
import {money,Num} from './planning-controls';
export function PlanningCashflow({budget:b,rules,editable,onChange}:{budget:Budget;rules:Rules;year:number;editable:boolean;onChange:(b:Budget)=>void}){
 const flow=onlineCashflow(b,rules),labels=onlinePeriods.map(p=>months[p.month]+' '+p.year);
 const change=(fn:(c:NonNullable<Budget['cashflow']>)=>void)=>{const n=clone(b);n.cashflow??={annualTarget:null,openingCash:null,payments:Array(12).fill(null)};fn(n.cashflow);onChange(n);};
 type Row={name:string;values?:(number|null)[];kind?:string;balance?:'opening'|'closing'};
 const rows:Row[]=[{name:'Opening cash balance',values:flow.opening,kind:'balance',balance:'opening'},{name:'CASH RECEIPTS',kind:'receipt-heading'},...flow.rows.filter(l=>['revenue','other_income'].includes(l.category)),{name:'Total cash receipts',values:flow.receipts,kind:'receipt-total'},{name:'CASH PAYMENTS',kind:'payment-heading'},...flow.rows.filter(l=>['direct_cost','operating_cost','tax'].includes(l.category)),...(flow.adjustment.some(v=>v!==0)?[{name:'Payment timing adjustments',values:flow.adjustment}]:[]),{name:'Total cash payments',values:flow.payments,kind:'payment-total'},{name:'Net cashflow',values:flow.net,kind:'net'},{name:'Closing cash balance',values:flow.closing,kind:'balance',balance:'closing'}];
 const summary=(row:Row,start:number,end:number)=>row.balance==='opening'?row.values![start]:row.balance==='closing'?row.values![end-1]:annual(row.values!.slice(start,end));
 const table=(monthly:boolean)=><div className="planning-scroll"><table className="cashflow-statement"><thead><tr><th>Cashflow (S$)</th>{monthly?labels.map(l=><th key={l}>{l}</th>):['2026 · Sep–Dec','2027 · Jan–Dec','Full projection'].map(l=><th key={l}>{l}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.name} className={row.kind||'cash-detail'}>{!row.values?<th colSpan={monthly?17:4}>{row.name}</th>:<><th>{row.name}</th>{(monthly?row.values:[summary(row,0,4),summary(row,4,16),summary(row,0,16)]).map((v,i)=><td key={i} className={v!==null&&v<0?'online-negative':''}>{money(v)}</td>)}</>}</tr>)}</tbody></table></div>;
 return <section id="online-cashflow"><h3>Cashflow projection · September 2026–December 2027</h3><p>Collections follow the monthly ratios from the 88Tuition workbook. September–December 2026 use those four calendar months’ shares of the annual target; 2027 uses the full year. Recurring expenses, including Marketing, start in September 2026. Launch Marketing and Coach Subsidy is spread equally over October 2026–January 2027.</p>
 <fieldset disabled={!editable}><div className="planning-fields"><label>Annual collection target override (S$)<Num label="Annual cash collection target" placeholder="Use budget revenue" money value={b.cashflow?.annualTarget??null} onChange={(v:number|null)=>change(c=>c.annualTarget=v)}/><small>Blank uses annual budget revenue: {money(annual(calculate(b,rules).revenue))}. The same annual target is used for both years.</small></label><label>Opening cash · 1 September 2026 (S$)<Num label="Opening cash balance" money min={-1e12} value={b.cashflow?.septemberOpening===undefined?3250000:b.cashflow.septemberOpening} onChange={(v:number|null)=>change(c=>c.septemberOpening=v)}/></label></div></fieldset>
 <div className="planning-kpis"><div><small>Receipts · 16 months</small><strong>{money(annual(flow.receipts))}</strong></div><div><small>Payments · 16 months</small><strong>{money(annual(flow.payments))}</strong></div><div><small>Net cashflow · 16 months</small><strong>{money(annual(flow.net))}</strong></div><div><small>Closing cash · December 2027</small><strong>{money(flow.closing[15])}</strong></div></div>
 <h4>Annual cashflow summary</h4>{table(false)}
 <h4>Monthly cashflow</h4>{table(true)}
 <p>Receipts are positive cash inflows. Payments are shown as positive amounts deducted from receipts. Closing cash = opening cash + receipts − payments. Teacher costs and referral commissions follow the seasonal collection amounts; recurring costs use the saved calendar-month amounts. Other income follows its saved monthly schedule.</p>
 <details className="planning-line"><summary>Collection ratios and payment timing</summary><div className="planning-scroll"><table><thead><tr><th>Collection share</th>{labels.map(l=><th key={l}>{l}</th>)}</tr></thead><tbody><tr><th>Share of annual collections</th>{onlinePeriods.map((p,i)=><td key={i}>{(cashflowSource.shares[p.month]*100).toFixed(2)}%</td>)}</tr></tbody></table></div><p>Blank payment overrides use the calculated costs above. A zero means no cash paid. Existing January–December overrides apply to 2027. Adjustments are shown separately so the statement reconciles.</p><fieldset disabled={!editable}><div className="planning-months">{labels.map((label,i)=><label key={label}>{label}<Num label={label+' cash payments override'} placeholder="Use calculated costs" money value={b.cashflow?.periodPayments?.[i]??(b.cashflow?.periodPayments?null:i>=4?b.cashflow?.payments[i-4]??null:null)} onChange={(v:number|null)=>change(c=>{c.periodPayments??=[...Array(4).fill(null),...c.payments];c.periodPayments[i]=v;})}/></label>)}</div></fieldset></details>
 <small>Source: {cashflowSource.file}, “{cashflowSource.sheet}” {cashflowSource.shareRange}, based on full-year 2025 collections. Only the collection percentages are used with this budget’s SGD amounts. Opening cash is S$32,500 unless edited. No additional financing or outstanding receivables/payables have been assumed.</small>
 </section>;
}
