export type Row = { id:string; [key:string]:any };
export type State = Record<string,Row[]>;
export const kinds=['users','boards','members','invites','groups','tasks','topics','messages','files','notifications','reads','activity','recurrences'];
export const uid=()=>crypto.randomUUID();
export const now=()=>new Date().toISOString();
export const today=(date=new Date())=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Singapore',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);
export const addDays=(date:string,n:number)=>new Date(Date.parse(date+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
export const initialStatuses=()=>[{id:'not-started',name:'Not started',color:'#E9EDF1',class:'open'},{id:'pending',name:'Pending',color:'#FFE3AD',class:'open'},{id:'wip',name:'WIP',color:'#C4E6E9',class:'active'},{id:'completed',name:'Completed',color:'#CCEBD7',class:'completed'}];
export function initial():State { const s=Object.fromEntries(kinds.map(k=>[k,[]])) as State; s.boards=['Directors','Marketing','Customer Relationship','Operations','AspireOnline','Technology'].map((name,i)=>({id:'board-'+i,name,statuses:initialStatuses(),columns:[],hidden:[],archived:false,version:1}));return s; }
export class AppError extends Error { status:number; constructor(message:string,status=400){super(message);this.status=status;} }
export function check(v:any,m='Access denied',status=403):asserts v {if(!v)throw new AppError(m,status);}
export const find=(s:State,k:string,id:string)=>{const r=s[k]?.find(x=>x.id===id);check(r,'Record unavailable',404);return r;};
const permission=(value:string)=>({View:1,Edit:2,Manage:3}[value as 'View']||0);
export const role=(s:State,u:Row,b:string)=>(!u.active||u.onboarding||u.deleted)?0:u.admin?4:Math.max(permission(s.members.find(m=>m.board===b&&m.user===u.id)?.role),permission(s.members.find(m=>m.board==='board-0'&&m.user===u.id)?.role));
export const member=(s:State,b:string,id:string)=>s.members.some(m=>(m.board===b||m.board==='board-0')&&m.user===id)&&s.users.some(u=>u.id===id&&u.active&&!u.deleted);
export function boardMemberships(s:State,b:string){
 const rows=s.members.filter(m=>m.board===b).map(m=>({...m}));
 if(b==='board-0')return rows;
 for(const director of s.members.filter(m=>m.board==='board-0'&&m.user)){
  const existing=rows.find(m=>m.user===director.user);
  if(existing){existing.directRole=existing.role;existing.role=permission(existing.role)>=permission(director.role)?existing.role:director.role;existing.directorsAccess=director.role;}
  else rows.push({...director,id:'directors:'+b+':'+director.user,board:b,inherited:true,directorsAccess:director.role});
 }
 return rows;
}
export const completed=(s:State,t:Row)=>find(s,'boards',t.board).statuses.find((x:Row)=>x.id===t.status)?.class==='completed';
export const archived=(s:State,t:Row)=>!!(t.archived||find(s,'boards',t.board).archived||find(s,'groups',t.group).archived||(t.parent&&find(s,'tasks',t.parent).archived));
export const overdue=(s:State,t:Row,d=today())=>!!t.due&&t.due<d&&!completed(s,t)&&!archived(s,t);
export function audit(s:State,u:Row,board:string,subject:string,action:string,before:any,after:any){s.activity.push({id:uid(),board,subject,user:u.id,action,before,after,at:now()});}
export function notify(s:State,u:Row,b:string,ids:string[],subject:string,text:string,event:string){for(const id of new Set(ids)){const recipient=s.users.find(x=>x.id===id);if(id!==u.id&&recipient&&role(s,recipient,b)&&!s.notifications.some(n=>n.event===event&&n.user===id))s.notifications.push({id:uid(),board:b,user:id,subject,text,event,read:false,at:now()});}}
export function legacyView(s:State,u:Row){check(u.active);const boards=s.boards.filter(b=>role(s,u,b.id)>0),ids=new Set(boards.map(b=>b.id));const {googleSub,...safeUser}=u;const v:any={me:safeUser,today:today(),pendingInvitations:s.invites.filter(i=>i.email===u.email&&i.state==='pending'&&i.expires>now()).map(i=>({id:i.id,token:i.token,boardName:find(s,'boards',i.board).name,role:i.role,expires:i.expires}))};for(const k of kinds)v[k]=s[k].filter(r=>k==='users'?u.admin||r.id===u.id||[...ids].some(b=>member(s,b,r.id))||s.messages.some(m=>m.user===r.id&&ids.has(m.board))||s.activity.some(a=>a.user===r.id&&ids.has(a.board)):k==='boards'?ids.has(r.id):ids.has(r.board));v.invites=v.invites.filter((r:Row)=>role(s,u,r.board)>=3).map(({token,...r}:Row)=>r);v.notifications=v.notifications.filter((r:Row)=>r.user===u.id);v.reads=v.reads.filter((r:Row)=>r.user===u.id);v.messages=v.messages.map((m:Row)=>m.removed&&m.user!==u.id&&role(s,u,m.board)<3?{...m,body:'',mentions:[]}:m);v.files=v.files.map(({key,...r}:Row)=>r);v.users=v.users.map(({googleSub,...r}:Row)=>r);v.activity=v.activity.map((a:Row)=>{if(a.action==='Message changed')return {...a,before:null,after:null};return a;});v.boards=v.boards.map((b:Row)=>({...b,access:role(s,u,b.id)}));return v;}
function editable(s:State,u:Row,b:string,min=1){check(role(s,u,b)>=min);check(!find(s,'boards',b).archived,'Restore the board before making changes');}
function taskOpen(s:State,t:Row){check(!archived(s,t),'Restore archived work before making changes');}
function version(r:Row,p:any){check(p.version===r.version,'This record changed. Refresh and review your draft before saving again.',409);}
const text=(v:any,max=10000)=>{check(typeof v==='string'&&v.length<=max,'Invalid text',400);return v;};
const date=(v:any)=>{if(!v)return;const parsed=typeof v==='string'?new Date(v+'T00:00:00Z'):new Date(NaN);check(typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(parsed.getTime())&&parsed.toISOString().slice(0,10)===v,'Invalid date',400);};
function validateTask(s:State,t:Row){check(text(t.title,500).trim(),'Title is required',400);const b=find(s,'boards',t.board);check(b.statuses.some((x:Row)=>x.id===t.status),'Unknown status',400);check(['Low','Medium','High'].includes(t.priority),'Invalid priority',400);date(t.start);date(t.due);check(!t.start||!t.due||t.due>=t.start,'Due date cannot precede start date',400);check(find(s,'groups',t.group).board===t.board,'Invalid group',400);if(t.assignee)check(member(s,t.board,t.assignee),'Choose an active board member',400);check(Array.isArray(t.team)&&t.team.every((id:string)=>member(s,t.board,id)),'Choose active supporting members',400);check(t.budget==null||t.budget===''||(typeof t.budget==='number'&&Number.isFinite(t.budget)&&t.budget>=0),'Budget must be a non-negative number',400);text(t.remark);text(t.description);check(Array.isArray(t.links)&&t.links.every((l:Row)=>typeof l.label==='string'&&/^https?:\/\//i.test(l.url)),'Use http or https links',400);for(const c of b.columns.filter((c:Row)=>!c.archived)){const v=t.custom?.[c.id];if(v==null||v==='')continue;if(c.type==='number')check(typeof v==='number'&&Number.isFinite(v),'Invalid number',400);if(c.type==='date')date(v);if(c.type==='member')check(member(s,t.board,v),'Invalid member',400);if(c.type==='link')check(typeof v==='string'?/^https?:\/\//i.test(v):v&&typeof v.label==='string'&&typeof v.url==='string'&&(!v.url||/^https?:\/\//i.test(v.url)),'Invalid link',400);if(c.type==='single-select')check(c.options.includes(v),'Invalid option',400);if(c.type==='multi-select')check(Array.isArray(v)&&v.every(x=>c.options.includes(x)),'Invalid options',400);}}
function dependencies(s:State,t:Row,ids:string[]){check(Array.isArray(ids),'Invalid dependencies',400);for(const id of ids){check(id!==t.id,'A task cannot depend on itself',400);check(find(s,'tasks',id).board===t.board,'Dependencies must be in the same board',400);const seen=new Set<string>();function walk(key:string):boolean{if(key===t.id)return true;if(seen.has(key))return false;seen.add(key);return (find(s,'tasks',key).depends||[]).some(walk);}check(!walk(id),'Dependency cycle rejected',400);}}
export function legacyMutate(s:State,u:Row,p:any):any{
 check(u.active);const op=p.op;
 if(op==='profile'){u.abbreviation=text(p.abbreviation,12).trim();check(u.abbreviation,'Abbreviation required',400);return u;}
 if(op==='user'){check(u.admin);const target=find(s,'users',p.id);check(target.id!==u.id||p.active!==false,'You cannot deactivate yourself',400);if(p.admin===false&&target.admin)check(s.users.filter(x=>x.admin&&x.active).length>1,'Keep an active administrator',400);if(typeof p.admin==='boolean')target.admin=p.admin;if(typeof p.active==='boolean')target.active=p.active;audit(s,u,'',target.id,'User permissions',null,{admin:target.admin,active:target.active});return target;}
 if(op==='board.create'){check(u.admin);const b={id:uid(),name:text(p.name,150),statuses:initialStatuses(),columns:[],hidden:[],archived:false,version:1};check(b.name.trim(),'Board name required',400);s.boards.push(b);audit(s,u,b.id,b.id,'Board created',null,b);return b;}
 if(op==='notifications.read'){for(const n of s.notifications.filter(n=>n.user===u.id&&role(s,u,n.board)&&(p.all||n.id===p.id)))n.read=p.read!==false;return;}
 if(op==='invite.accept'){const i=s.invites.find(i=>i.token===p.token);check(i&&i.email===u.email&&i.state==='pending'&&i.expires>now(),'Invitation unavailable or email does not match',403);check(!find(s,'boards',i.board).archived,'Board is archived',400);s.members=s.members.filter(m=>!(m.board===i.board&&m.user===u.id));s.members.push({id:uid(),board:i.board,user:u.id,role:i.role});i.state='accepted';audit(s,u,i.board,i.id,'Invitation accepted',null,u.email);return i.board;}
 const b=String(p.board||'');check(role(s,u,b)>0);const board=find(s,'boards',b);
 if(op==='board.update'){check(u.admin);version(board,p);const before={...board};if(p.name!==undefined)board.name=text(p.name,150);if(typeof p.archived==='boolean')board.archived=p.archived;board.version++;audit(s,u,b,b,'Board changed',before,board);return board;}
 if(op==='chat.read'){const context=s.tasks.find(t=>t.id===p.subject)||s.topics.find(t=>t.id===p.subject);check(context&&context.board===b,'Conversation unavailable',404);s.reads=s.reads.filter(r=>!(r.subject===p.subject&&r.user===u.id));s.reads.push({id:uid(),board:b,subject:p.subject,user:u.id,at:now(),last:s.messages.filter(m=>m.subject===p.subject&&!m.removed).at(-1)?.id});return;}
 editable(s,u,b);
 if(op==='member'){check(role(s,u,b)>=3);find(s,'users',p.user);const prev=s.members.find(m=>m.board===b&&m.user===p.user);check(prev||(u.admin&&p.user===u.id),'Invite new members by email; direct membership creation is not allowed',400);if(p.role)check(['View','Edit','Manage'].includes(p.role),'Invalid role',400);s.members=s.members.filter(m=>!(m.board===b&&m.user===p.user));if(!p.role){const email=find(s,'users',p.user).email;for(const i of s.invites.filter(i=>i.board===b&&i.email===email&&i.state==='pending'))i.state='cancelled';}if(p.role)s.members.push({id:uid(),board:b,user:p.user,role:p.role});audit(s,u,b,p.user,'Membership changed',prev,p.role||'Revoked');return;}
 if(op==='invite'){check(role(s,u,b)>=3);check(typeof p.email==='string'&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(p.email),'Valid email required',400);check(['View','Edit','Manage'].includes(p.role),'Invalid role',400);for(const old of s.invites.filter(i=>i.board===b&&i.email===p.email.trim().toLowerCase()&&i.state==='pending'))old.state='cancelled';const i={id:uid(),board:b,email:p.email.trim().toLowerCase(),role:p.role,token:uid()+uid(),expires:new Date(Date.now()+7*86400000).toISOString(),state:'pending',delivery:'queued',inviter:u.id,at:now()};s.invites.push(i);audit(s,u,b,i.id,'Invitation created',null,i.email);return i;}
 if(op==='invite.update'){check(role(s,u,b)>=3);const i=find(s,'invites',p.id);check(i.board===b);check(i.state!=='accepted','Invitation already accepted',400);if(p.cancel)i.state='cancelled';else{i.state='pending';i.token=uid()+uid();i.expires=new Date(Date.now()+7*86400000).toISOString();i.delivery='queued';}return i;}
 if(op==='settings'){check(role(s,u,b)>=3);version(board,p);const before=structuredClone(board);if(p.statuses){check(Array.isArray(p.statuses)&&p.statuses.length>=2,'At least two statuses required',400);check(new Set(p.statuses.map((x:Row)=>x.id)).size===p.statuses.length,'Duplicate status',400);check(p.statuses.some((x:Row)=>x.class==='open')&&p.statuses.some((x:Row)=>x.class==='completed'),'Keep open and completed statuses',400);for(const x of p.statuses)check(x.id&&text(x.name,50).trim()&&['open','active','completed'].includes(x.class)&&/^#[0-9a-f]{6}$/i.test(x.color),'Invalid status',400);for(const t of s.tasks.filter(t=>t.board===b&&!p.statuses.some((x:Row)=>x.id===t.status))){check(p.statuses.some((x:Row)=>x.id===p.replacement),'Choose a replacement status for affected tasks',400);t.status=p.replacement;t.version++;}board.statuses=p.statuses;}
 if(p.columns){check(Array.isArray(p.columns),'Invalid columns',400);for(const c of p.columns){check(c.id&&text(c.name,80).trim()&&['text','number','date','single-select','multi-select','member','link'].includes(c.type),'Invalid column',400);if(c.type.includes('select'))check(Array.isArray(c.options),'Supply options',400);const prev=board.columns.find((x:Row)=>x.id===c.id);check(!prev||prev.type===c.type,'Column type cannot change; archive and add a new field',400);}const removed=board.columns.filter((c:Row)=>!p.columns.some((x:Row)=>x.id===c.id));check(removed.every((c:Row)=>(p.deleteColumns||[]).includes(c.id)),'Confirm column deletion first',400);for(const c of removed){for(const t of s.tasks.filter(t=>t.board===b)){if(t.custom&&c.id in t.custom){delete t.custom[c.id];t.version++;}}for(const r of s.recurrences.filter(r=>r.board===b))for(const t of r.template||[])if(t.custom)delete t.custom[c.id];}board.columns=p.columns;board.hidden=(board.hidden||[]).filter((id:string)=>!removed.some((c:Row)=>c.id===id));}
 if(p.hidden)board.hidden=p.hidden.filter((x:string)=>['assignee','team','priority','start','due','remark','links','budget',...board.columns.map((c:Row)=>c.id)].includes(x));board.version++;audit(s,u,b,b,'Board settings',before,board);return board;}
 if(op==='group.create'){const g={id:uid(),board:b,name:text(p.name,150),color:p.color||'#287D83',order:s.groups.filter(g=>g.board===b).length,archived:false,version:1};check(g.name.trim(),'Group name required',400);s.groups.push(g);audit(s,u,b,g.id,'Group created',null,g);return g;}
 if(op==='group.update'){const g=find(s,'groups',p.id);check(g.board===b);check(role(s,u,b)>=(p.archived!==undefined?3:2));version(g,p);check(!g.archived||p.archived===false,'Restore group first',400);const before={...g};for(const key of ['name','color','order','archived'])if(p[key]!==undefined)g[key]=p[key];check(text(g.name,150).trim(),'Group name required',400);check(Number.isFinite(g.order)&&/^#[0-9a-f]{6}$/i.test(g.color),'Invalid group order or colour',400);g.version++;audit(s,u,b,g.id,'Group changed',before,g);return g;}
 if(op==='task.create'){check(role(s,u,b)>=2);const parent=p.parent?find(s,'tasks',p.parent):null;check(!parent||(parent.board===b&&!parent.parent),'Only one subtask level is supported',400);if(parent)taskOpen(s,parent);const t={id:uid(),board:b,group:parent?.group||p.group,parent:parent?.id||null,title:p.title||'New task',status:board.statuses.find((x:Row)=>x.class==='open').id,assignee:null,team:[],budget:null,remark:'',description:'',priority:'Medium',start:'',due:'',order:Math.max(-1,...s.tasks.filter(x=>x.board===b&&x.group===(parent?.group||p.group)&&(x.parent||null)===(parent?.id||null)).map(x=>x.order||0))+1,links:[],custom:{},depends:[],archived:false,version:1,createdBy:u.id,updatedBy:u.id,createdAt:now(),updatedAt:now()};check(!find(s,'groups',t.group).archived,'Group is archived',400);validateTask(s,t);s.tasks.push(t);audit(s,u,b,t.id,'Task created',null,t);return t;}
 if(op==='task.update'){const t=find(s,'tasks',p.id);check(t.board===b);version(t,p);const fields=Object.keys(p.changes||{});check(fields.length&&fields.every(x=>['title','group','status','assignee','team','budget','remark','description','priority','start','due','links','custom','depends','archived'].includes(x)),'Unknown task field',400);check(role(s,u,b)>=2||(role(s,u,b)>=1&&t.assignee===u.id&&fields.every(x=>['status','remark'].includes(x))));if(fields.includes('archived'))check(role(s,u,b)>=3);if(!(fields.length===1&&p.changes.archived===false))taskOpen(s,t);const before=structuredClone(t),next={...t,...p.changes};if(next.assignee!==t.assignee||JSON.stringify(next.team)!==JSON.stringify(t.team))validateTask(s,next);else validateTask(s,{...next,assignee:member(s,b,next.assignee)?next.assignee:null,team:next.team.filter((id:string)=>member(s,b,id))});check(!find(s,'groups',next.group).archived||p.changes.archived===false,'Group is archived',400);if(t.parent)check(next.group===find(s,'tasks',t.parent).group,'Move the parent task instead',400);dependencies(s,t,next.depends);if(!completed(s,t)&&board.statuses.find((x:Row)=>x.id===next.status)?.class==='completed'&&s.tasks.some(x=>x.parent===t.id&&!completed(s,x)&&!archived(s,x)))check(p.confirmIncomplete,'This parent has unfinished subtasks. Confirm completion to continue.',409);Object.assign(t,next,{version:t.version+1,updatedAt:now(),updatedBy:u.id});if(before.status!==t.status)t.completedAt=completed(s,t)?now():null;if(before.group!==t.group)for(const child of s.tasks.filter(c=>c.parent===t.id)){child.group=t.group;child.version++;}audit(s,u,b,t.id,'Task updated',before,t);notify(s,u,b,[...(before.assignee!==t.assignee&&t.assignee?[t.assignee]:[]),...t.team.filter((id:string)=>!before.team.includes(id))],t.id,'You were added to '+t.title,uid());return t;}
 if(op==='topic.create'){const t={id:uid(),board:b,title:text(p.title,200),createdBy:u.id,at:now()};check(t.title.trim(),'Topic required',400);s.topics.push(t);return t;}
 if(op.startsWith('chat.')||op==='file.remove'){
 const subject=p.subject;const context=s.tasks.find(t=>t.id===subject)||s.topics.find(t=>t.id===subject);check(context&&context.board===b,'Conversation unavailable',404);if(context.group)taskOpen(s,context);
 if(op==='chat.read'){s.reads=s.reads.filter(r=>!(r.subject===subject&&r.user===u.id));const messages=s.messages.filter(m=>m.subject===subject);s.reads.push({id:uid(),board:b,subject,user:u.id,at:now(),last:messages.at(-1)?.id});return;}
 if(op==='chat.post'){const body=text(p.body,20000);const files=p.files||[];check(body.trim()||files.length,'Write a message or attach a file',400);check(Array.isArray(p.mentions||[])&&(p.mentions||[]).every((id:string)=>member(s,b,id)),'Mention active board members only',400);if(p.reply){const reply=find(s,'messages',p.reply);check(reply.subject===subject&&!reply.removed,'Reply unavailable',400);}for(const id of files){const f=find(s,'files',id);check(f.board===b&&f.subject===subject&&f.user===u.id&&!f.message&&!f.removed,'Attachment unavailable',400);}const m={id:uid(),board:b,subject,user:u.id,body,mentions:p.mentions||[],reply:p.reply||null,at:now(),version:1,removed:false};s.messages.push(m);for(const id of files)find(s,'files',id).message=m.id;notify(s,u,b,[...m.mentions,...s.messages.filter(x=>x.subject===subject&&!x.removed).map(x=>x.user)],subject,(m.mentions.length?'Mention or reply: ':'New reply: ')+context.title,m.id);audit(s,u,b,subject,'Message posted',null,m.id);return m;}
 if(op==='file.remove'){const f=find(s,'files',p.id);check(f.board===b&&f.subject===subject);check(f.user===u.id||role(s,u,b)>=3);f.removed=p.removed!==false;audit(s,u,b,subject,'Attachment removal changed',null,f.id);return;}
 const m=find(s,'messages',p.id);check(m.board===b&&m.subject===subject);version(m,p);check(m.user===u.id||(op==='chat.remove'&&role(s,u,b)>=3));const before={...m};if(op==='chat.edit')m.body=text(p.body,20000);else if(op==='chat.remove')m.removed=p.removed!==false;else throw new AppError('Unknown chat action');m.version++;m.editedAt=now();audit(s,u,b,subject,'Message changed',before,m);return m;}
 if(op==='recurrence'){check(role(s,u,b)>=2);const t=find(s,'tasks',p.id);check(t.board===b&&!t.parent,'Recurrence is for parent tasks',400);taskOpen(s,t);let r=s.recurrences.find(r=>r.task===t.id);if(p.action){check(r,'Recurrence unavailable',404);check(['pause','resume','end'].includes(p.action),'Invalid recurrence action',400);check(r.state!=='ended','An ended recurrence cannot resume; create a new schedule',400);if(p.action==='pause')runRecurrences(s);r.state=p.action==='resume'?'active':p.action==='pause'?'paused':'ended';if(p.action==='resume')r.cursor=today();return r;}
 check(['weekly','monthly'].includes(p.frequency),'Invalid frequency',400);date(p.start);date(p.end);check(p.start&&(!p.end||p.end>=p.start),'Invalid recurrence dates',400);check(Number.isInteger(p.day)&&p.day>=(p.frequency==='weekly'?0:1)&&p.day<=(p.frequency==='weekly'?6:31),'Invalid schedule day',400);check(Number.isInteger(p.offset)&&p.offset>=0&&p.offset<=365,'Invalid due offset',400);const template=[t,...s.tasks.filter(x=>x.parent===t.id&&!x.archived)].map(x=>structuredClone(x));if(r?.state==='ended')r=undefined;if(!r){r={id:uid(),board:b,task:t.id,cursor:addDays(p.start,-1),state:'active'};s.recurrences.push(r);}Object.assign(r,{frequency:p.frequency,start:p.start,end:p.end||'',day:p.day,offset:p.offset,template});audit(s,u,b,t.id,'Recurrence template saved',null,r.id);return r;}
 throw new AppError('Unknown action');
}
export function runRecurrences(s:State,date=today()){let count=0;for(const r of s.recurrences){if(r.state!=='active')continue;const source=s.tasks.find(t=>t.id===r.task);if(!source||archived(s,source))continue;let d=addDays(r.cursor,1);for(let steps=0;d<=date&&steps<3660;steps++,d=addDays(d,1)){if(d<r.start)continue;if(r.end&&d>r.end){r.state='ended';break;}const dt=new Date(d+'T00:00:00Z');const day=Math.min(r.day,new Date(Date.UTC(dt.getUTCFullYear(),dt.getUTCMonth()+1,0)).getUTCDate());const match=r.frequency==='weekly'?dt.getUTCDay()===r.day:dt.getUTCDate()===day;if(match&&!s.tasks.some(t=>t.occurrence===r.id+':'+d)){if(count>=20)return count;const ids=new Map(r.template.map((t:Row)=>[t.id,uid()]));for(const old of r.template){const t=structuredClone(old);t.id=ids.get(old.id);t.parent=old.parent?ids.get(old.parent):null;t.group=source.group;t.status=find(s,'boards',r.board).statuses.find((x:Row)=>x.class==='open').id;t.remark='';t.version=1;t.archived=false;t.completedAt=null;t.occurrence=r.id+':'+d;t.depends=(old.depends||[]).filter((id:string)=>ids.has(id)).map((id:string)=>ids.get(id));const anchor=r.template[0].start||r.start;const offset=(x:string)=>Math.round((Date.parse(x)-Date.parse(anchor))/86400000);t.start=old.parent?(old.start?addDays(d,offset(old.start)):''):d;t.due=old.parent?(old.due?addDays(d,offset(old.due)):''):addDays(d,r.offset);t.createdAt=now();t.updatedAt=now();t.updatedBy='scheduler';s.tasks.push(t);notify(s,{id:'scheduler'},r.board,[t.assignee,...t.team].filter(Boolean),t.id,'New recurring assignment: '+t.title,t.id);s.activity.push({id:uid(),board:r.board,subject:t.id,user:'scheduler',action:'Occurrence created',at:now()});}count++;}r.cursor=d;}}return count;}
export {workspaceView as view,workspaceMutate as mutate} from './people';
