import {BudgetDriver,deriveLine,validDriver,withKnownDrivers} from './budget-drivers';
import {AppError,role,Row,State} from './model';
export type Entity={id:string;name:string;kind:'branch'|'online'|'coaching'|'company';parent_id:string|null;board_id:string|null;revision:number};
export type Price={id:string;product:string;level:string;category:string;unit:string;amount:number|null;group?:string;tier?:number;units?:number;previous?:number|null;source?:string;unavailable?:boolean};
export type Rules={prices:Price[];teacher:Record<string,number|null>;rates:Record<string,Record<string,Record<string,(number|null)[]>>>};
export type Line={id:string;name:string;category:'revenue'|'direct_cost'|'operating_cost'|'other_income'|'tax';method:'manual'|'quantity'|'percent';values:(number|null)[];priceId?:string;baseId?:string;rate:number|null;rateSource?:'custom'|'teacher'|'commission';product?:string;channel?:string;saleType?:string;driver?:BudgetDriver};
export type Budget={lines:Line[];notes:string;cashflow?:{annualTarget:number|null;openingCash:number|null;payments:(number|null)[];septemberOpening?:number|null;periodPayments?:(number|null)[]}};
export const products=['A','B','C','D'];
export const channels=['Physical Centre','Online','Cold Call'];
export const recipients=['CRE','CRM','Branch','Aspire Online'];
export const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
export const clone=<T,>(x:T):T=>JSON.parse(JSON.stringify(x));
const fail=(ok:unknown,message:string)=>{if(!ok)throw new AppError(message,400);};
const number=(x:unknown,max=1e12)=>x===null||typeof x==='number'&&Number.isFinite(x)&&x>=0&&x<=max;
const text=(s:unknown)=>typeof s==='string'&&!!s.trim()&&s.length<=200;
export function manager(_s:State,u:Row){return !!u.active&&!u.onboarding&&!u.deleted&&!!u.admin;}
export function analyst(u:Row){return !!u.active&&!u.onboarding&&!u.deleted&&(!!u.admin||(u.roles||[]).some((r:string)=>['Director','Senior Manager'].includes(r)));}
export function entityAccess(s:State,u:Row,_e:Entity){if(!u.active||u.onboarding||u.deleted)return 0;return manager(s,u)?3:analyst(u)?2:1;}
export function validateRules(r:Rules){
 fail(r&&Array.isArray(r.prices)&&r.prices.length<=500,'Invalid price list');const ids=new Set<string>();
 for(const p of r.prices){fail(text(p.id)&&!ids.has(p.id),'Price IDs must be unique');ids.add(p.id);fail(products.includes(p.product)&&text(p.level)&&text(p.category)&&text(p.unit)&&number(p.amount)&& (p.amount===null||Number.isInteger(p.amount)),'Enter valid prices in cents or leave unknown prices blank');}
 for(const p of products){fail(number(r.teacher?.[p],100),'Teacher shares must be 0–100% or blank');for(const stage of ['initial','renewal','upsell'])for(const channel of channels.filter(c=>c!=='Online'||['A','B'].includes(p))){const row=r.rates?.[stage]?.[channel]?.[p];fail(Array.isArray(row)&&row.length===4&&row.every(v=>number(v,100)),'Commission allocations must contain four percentages or blanks');}}
}
export function validateBudget(b:Budget,r:Rules){
 fail(b&&Array.isArray(b.lines)&&b.lines.length>0&&b.lines.length<=100&&typeof b.notes==='string'&&b.notes.length<=10000,'Supply 1–100 P&L lines');const ids=new Set<string>();
 if(b.cashflow!==undefined){const c=b.cashflow;fail(c&&number(c.annualTarget)&&(c.openingCash===null||typeof c.openingCash==='number'&&Number.isFinite(c.openingCash)&&Math.abs(c.openingCash)<=1e12)&&[c.annualTarget,c.openingCash].every(v=>v===null||Number.isInteger(v))&&Array.isArray(c.payments)&&c.payments.length===12&&c.payments.every(v=>number(v)&&(v===null||Number.isInteger(v))),'Invalid cashflow assumptions');
 if(c.septemberOpening!==undefined)fail(c.septemberOpening===null||Number.isInteger(c.septemberOpening)&&Math.abs(c.septemberOpening)<=1e12,'Invalid opening cash');
 if(c.periodPayments!==undefined)fail(Array.isArray(c.periodPayments)&&c.periodPayments.length===16&&c.periodPayments.every(v=>number(v)&&(v===null||Number.isInteger(v))),'Invalid period cash payments');
 }
 for(const l of b.lines){fail(validDriver(l),'Invalid calculation assumptions');fail(text(l.id)&&!ids.has(l.id),'P&L line IDs must be unique');ids.add(l.id);fail(text(l.name)&&['revenue','direct_cost','operating_cost','other_income','tax'].includes(l.category),'Invalid P&L line');fail(['manual','quantity','percent'].includes(l.method)&&Array.isArray(l.values)&&l.values.length===12&&l.values.every(v=>number(v)),'Enter twelve non-negative monthly values or blanks');if(l.method==='manual')fail(l.values.every(v=>v===null||Number.isInteger(v)),'Amounts must be whole cents');if(l.method==='quantity')fail(r.prices.some(p=>p.id===l.priceId),'Choose a price for each quantity line');if(l.method==='percent'){fail(b.lines.some(x=>x.id===l.baseId),'Choose a base line');fail(['custom','teacher','commission'].includes(l.rateSource||'custom'),'Invalid percentage source');if(!l.rateSource||l.rateSource==='custom')fail(number(l.rate,1000),'Invalid percentage');else{fail(products.includes(l.product||''),'Choose a product');if(l.rateSource==='commission')fail(['initial','renewal','upsell'].includes(l.saleType||'')&&channels.includes(l.channel||'')&&(l.channel!=='Online'||['A','B'].includes(l.product||'')),'Invalid commission selection');}}}
 const visit=(id:string,stack:Set<string>)=>{fail(!stack.has(id),'Circular P&L formulas are not allowed');const l=b.lines.find(x=>x.id===id)!;if(l.method==='percent')visit(l.baseId!,new Set([...stack,id]));};b.lines.forEach(l=>visit(l.id,new Set()));
}
export function rateFor(l:Line,r:Rules){l=deriveLine(l);if(l.rateSource==='teacher')return r.teacher[l.product!];if(l.rateSource==='commission'){const a=r.rates[l.saleType!][l.channel!][l.product!];return a.some(x=>x===null)?null:a.reduce<number>((a,b)=>a+b!,0);}return l.rate;}
export function calculate(b:Budget,r:Rules){validateBudget(b,r);const rows:Record<string,(number|null)[]>=Object.create(null);const resolve=(id:string):(number|null)[]=>{if(rows[id])return rows[id];const l=deriveLine(b.lines.find(x=>x.id===id)!);return rows[id]=l.values.map((v,i)=>{if(l.method==='manual')return v;if(l.method==='quantity'){const price=r.prices.find(p=>p.id===l.priceId)!.amount;return v===null||price===null?null:Math.round(v*price);}const base=resolve(l.baseId!)[i],rate=rateFor(l,r);return base===null||rate===null?null:l.rateSource==='commission'?r.rates[l.saleType!][l.channel!][l.product!].reduce<number>((sum,rate)=>sum+roundedCommission(base,rate!),0):Math.round(base*rate/100);});};b.lines.forEach(l=>resolve(l.id));const total=(category:string)=>months.map((_,i)=>{const vals=b.lines.filter(l=>l.category===category).map(l=>rows[l.id][i]);return vals.some(x=>x===null)?null:vals.reduce<number>((a,v)=>a+v!,0);});const revenue=total('revenue'),direct=total('direct_cost'),operating=total('operating_cost'),other=total('other_income'),tax=total('tax');const subtract=(a:(number|null)[],c:(number|null)[])=>a.map((v,i)=>v===null||c[i]===null?null:v-c[i]!);const gross=subtract(revenue,direct),op=subtract(gross,operating);const net=op.map((v,i)=>[v,other[i],tax[i]].some(x=>x===null)?null:v!+other[i]!-tax[i]!);return {rows,revenue,gross,operating:op,net};}
export const annual=(a:(number|null)[])=>a.some(x=>x===null)?null:a.reduce<number>((s,v)=>s+v!,0);
export const roundedCommission=(base:number,rate:number)=>Math.round(base*rate/10000)*100;
export function earnings(fee:number|null,teacher:number|null,rates:(number|null)[],basis:'gross'|'net'){const t=fee===null||teacher===null?null:Math.round(fee*teacher/100);const base=basis==='gross'?fee:fee===null||t===null?null:fee-t;const commissions=rates.map(r=>base===null||r===null?null:roundedCommission(base,r));const retained=fee===null||t===null||commissions.some(v=>v===null)?null:fee-t-commissions.reduce<number>((a,b)=>a+b!,0);return {teacher:t,commissions,retained,percent:fee&&retained!==null?retained/fee*100:null};}
export function budgetTemplate(online=false):Budget{
 const manual=(id:string,name:string,category:Line['category'],amount:number):Line=>({id,name,category,method:'manual',values:Array(12).fill(amount),rate:null});
 if(!online)return {notes:'Enter monthly amounts in S$. Blank means unknown; 0 means confirmed zero.',lines:[manual('sales','Sales revenue','revenue',0),manual('teacher','Teacher costs','direct_cost',0),manual('rent','Rent','operating_cost',0),manual('staff','Staff costs','operating_cost',0)]};
 const c=196888.32,d=131258.88;const revenue=(id:string,name:string,year:number)=>({...manual(id,name,'revenue',0),values:months.map((_,i)=>Math.round(year/12*(.25+i*.75/11)*100))});
 const percent=(id:string,name:string,baseId:string,rate:number):Line=>({id,name,category:'direct_cost',method:'percent',baseId,rate,rateSource:'custom',values:Array(12).fill(0)});
 return withKnownDrivers({notes:'Aspire Online 2027 source management ramp case: external mix 60:40; 30% AH referrals; C/D commission 15%/40%; teacher 50%; January at 25% of run-rate, December at 100%. AH revenue: 2,833 × S$12 × 3. Budget-specific assumptions are separate from the published commission settings. Cashflow uses the 88Tuition 2025 collection pattern with separately stated payment and opening cash assumptions.',lines:[revenue('c','Product C revenue',c),revenue('d','Product D revenue',d),manual('ah','AH access fees','revenue',849900),percent('teachers','Live tutorial teachers','c',50),percent('cc','C referral commission','c',4.5),percent('dc','D referral commission','d',12),...([['tech','Technical support',6500],['staff','Staff Cost',8500],['hosting','Hosting and subscriptions',2000],['curriculum','Curriculum support',3000],['director','Director fee including 9% CPF',1090],['marketing','Marketing',2000]] as const).map(([id,name,amount])=>manual(id,name,'operating_cost',amount*100)),{...manual('launch','Launch marketing and coaches subsidy','operating_cost',0),values:[3000000,...Array(11).fill(0)]}]});
}
