import type {Rules} from './planning';
// 2027 values from supplied workbook; its worksheet is named Price List 2026.
export const seedRules:Rules={
  "prices": [
    {
      "id": "A-8-9",
      "product": "A",
      "level": "Primary 1–2",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 9200,
      "group": "Academic coaching",
      "tier": 0,
      "units": 1,
      "previous": 9200,
      "source": "Price List 2026!I8",
      "unavailable": false
    },
    {
      "id": "A-8-10",
      "product": "A",
      "level": "Primary 1–2",
      "category": "Lite",
      "unit": "lesson",
      "amount": 8300,
      "group": "Academic coaching",
      "tier": 1,
      "units": 8,
      "previous": 8200,
      "source": "Price List 2026!J8",
      "unavailable": false
    },
    {
      "id": "A-8-11",
      "product": "A",
      "level": "Primary 1–2",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 7400,
      "group": "Academic coaching",
      "tier": 2,
      "units": 12,
      "previous": 7200,
      "source": "Price List 2026!K8",
      "unavailable": false
    },
    {
      "id": "A-8-12",
      "product": "A",
      "level": "Primary 1–2",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 6900,
      "group": "Academic coaching",
      "tier": 3,
      "units": 36,
      "previous": 6500,
      "source": "Price List 2026!L8",
      "unavailable": false
    },
    {
      "id": "A-9-9",
      "product": "A",
      "level": "Primary 3–4",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 9200,
      "group": "Academic coaching",
      "tier": 0,
      "units": 1,
      "previous": 9200,
      "source": "Price List 2026!I9",
      "unavailable": false
    },
    {
      "id": "A-9-10",
      "product": "A",
      "level": "Primary 3–4",
      "category": "Lite",
      "unit": "lesson",
      "amount": 8300,
      "group": "Academic coaching",
      "tier": 1,
      "units": 8,
      "previous": 8200,
      "source": "Price List 2026!J9",
      "unavailable": false
    },
    {
      "id": "A-9-11",
      "product": "A",
      "level": "Primary 3–4",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 7400,
      "group": "Academic coaching",
      "tier": 2,
      "units": 12,
      "previous": 7200,
      "source": "Price List 2026!K9",
      "unavailable": false
    },
    {
      "id": "A-9-12",
      "product": "A",
      "level": "Primary 3–4",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 6900,
      "group": "Academic coaching",
      "tier": 3,
      "units": 36,
      "previous": 6500,
      "source": "Price List 2026!L9",
      "unavailable": false
    },
    {
      "id": "A-10-9",
      "product": "A",
      "level": "Primary 5–6",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 10200,
      "group": "Academic coaching",
      "tier": 0,
      "units": 1,
      "previous": 10200,
      "source": "Price List 2026!I10",
      "unavailable": false
    },
    {
      "id": "A-10-10",
      "product": "A",
      "level": "Primary 5–6",
      "category": "Lite",
      "unit": "lesson",
      "amount": 9700,
      "group": "Academic coaching",
      "tier": 1,
      "units": 8,
      "previous": 9200,
      "source": "Price List 2026!J10",
      "unavailable": false
    },
    {
      "id": "A-10-11",
      "product": "A",
      "level": "Primary 5–6",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 8700,
      "group": "Academic coaching",
      "tier": 2,
      "units": 12,
      "previous": 8200,
      "source": "Price List 2026!K10",
      "unavailable": false
    },
    {
      "id": "A-10-12",
      "product": "A",
      "level": "Primary 5–6",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 8200,
      "group": "Academic coaching",
      "tier": 3,
      "units": 36,
      "previous": 7500,
      "source": "Price List 2026!L10",
      "unavailable": false
    },
    {
      "id": "A-11-9",
      "product": "A",
      "level": "Secondary 1–2 / IP·IB Y1–2",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 11400,
      "group": "Academic coaching",
      "tier": 0,
      "units": 1,
      "previous": 11200,
      "source": "Price List 2026!I11",
      "unavailable": false
    },
    {
      "id": "A-11-10",
      "product": "A",
      "level": "Secondary 1–2 / IP·IB Y1–2",
      "category": "Lite",
      "unit": "lesson",
      "amount": 10800,
      "group": "Academic coaching",
      "tier": 1,
      "units": 8,
      "previous": 10200,
      "source": "Price List 2026!J11",
      "unavailable": false
    },
    {
      "id": "A-11-11",
      "product": "A",
      "level": "Secondary 1–2 / IP·IB Y1–2",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 9700,
      "group": "Academic coaching",
      "tier": 2,
      "units": 12,
      "previous": 9200,
      "source": "Price List 2026!K11",
      "unavailable": false
    },
    {
      "id": "A-11-12",
      "product": "A",
      "level": "Secondary 1–2 / IP·IB Y1–2",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 9100,
      "group": "Academic coaching",
      "tier": 3,
      "units": 36,
      "previous": 8500,
      "source": "Price List 2026!L11",
      "unavailable": false
    },
    {
      "id": "A-12-9",
      "product": "A",
      "level": "Secondary 3–5",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 11900,
      "group": "Academic coaching",
      "tier": 0,
      "units": 1,
      "previous": 11700,
      "source": "Price List 2026!I12",
      "unavailable": false
    },
    {
      "id": "A-12-10",
      "product": "A",
      "level": "Secondary 3–5",
      "category": "Lite",
      "unit": "lesson",
      "amount": 11300,
      "group": "Academic coaching",
      "tier": 1,
      "units": 8,
      "previous": 10700,
      "source": "Price List 2026!J12",
      "unavailable": false
    },
    {
      "id": "A-12-11",
      "product": "A",
      "level": "Secondary 3–5",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 10100,
      "group": "Academic coaching",
      "tier": 2,
      "units": 12,
      "previous": 9700,
      "source": "Price List 2026!K12",
      "unavailable": false
    },
    {
      "id": "A-12-12",
      "product": "A",
      "level": "Secondary 3–5",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 9500,
      "group": "Academic coaching",
      "tier": 3,
      "units": 36,
      "previous": 9000,
      "source": "Price List 2026!L12",
      "unavailable": false
    },
    {
      "id": "A-13-9",
      "product": "A",
      "level": "JC / IB / IP Y5–Y6",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 14600,
      "group": "Academic coaching",
      "tier": 0,
      "units": 1,
      "previous": 14300,
      "source": "Price List 2026!I13",
      "unavailable": false
    },
    {
      "id": "A-13-10",
      "product": "A",
      "level": "JC / IB / IP Y5–Y6",
      "category": "Lite",
      "unit": "lesson",
      "amount": 13900,
      "group": "Academic coaching",
      "tier": 1,
      "units": 8,
      "previous": 13300,
      "source": "Price List 2026!J13",
      "unavailable": false
    },
    {
      "id": "A-13-11",
      "product": "A",
      "level": "JC / IB / IP Y5–Y6",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 12400,
      "group": "Academic coaching",
      "tier": 2,
      "units": 12,
      "previous": 12300,
      "source": "Price List 2026!K13",
      "unavailable": false
    },
    {
      "id": "A-13-12",
      "product": "A",
      "level": "JC / IB / IP Y5–Y6",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 11700,
      "group": "Academic coaching",
      "tier": 3,
      "units": 36,
      "previous": 11600,
      "source": "Price List 2026!L13",
      "unavailable": false
    },
    {
      "id": "A-14-9",
      "product": "A",
      "level": "IB / IP Y3–Y4",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 13200,
      "group": "Academic coaching",
      "tier": 0,
      "units": 1,
      "previous": 13200,
      "source": "Price List 2026!I14",
      "unavailable": false
    },
    {
      "id": "A-14-10",
      "product": "A",
      "level": "IB / IP Y3–Y4",
      "category": "Lite",
      "unit": "lesson",
      "amount": 12500,
      "group": "Academic coaching",
      "tier": 1,
      "units": 8,
      "previous": 12200,
      "source": "Price List 2026!J14",
      "unavailable": false
    },
    {
      "id": "A-14-11",
      "product": "A",
      "level": "IB / IP Y3–Y4",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 11200,
      "group": "Academic coaching",
      "tier": 2,
      "units": 12,
      "previous": 11200,
      "source": "Price List 2026!K14",
      "unavailable": false
    },
    {
      "id": "A-14-12",
      "product": "A",
      "level": "IB / IP Y3–Y4",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 10600,
      "group": "Academic coaching",
      "tier": 3,
      "units": 36,
      "previous": 10500,
      "source": "Price List 2026!L14",
      "unavailable": false
    },
    {
      "id": "B-20-9",
      "product": "B",
      "level": "Primary 1–2",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 6900,
      "group": "Physical tutorial",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I20",
      "unavailable": false
    },
    {
      "id": "B-20-10",
      "product": "B",
      "level": "Primary 1–2",
      "category": "Lite",
      "unit": "lesson",
      "amount": 6400,
      "group": "Physical tutorial",
      "tier": 1,
      "units": 4,
      "previous": null,
      "source": "Price List 2026!J20",
      "unavailable": false
    },
    {
      "id": "B-20-11",
      "product": "B",
      "level": "Primary 1–2",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 5900,
      "group": "Physical tutorial",
      "tier": 2,
      "units": 12,
      "previous": null,
      "source": "Price List 2026!K20",
      "unavailable": false
    },
    {
      "id": "B-20-12",
      "product": "B",
      "level": "Primary 1–2",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 5500,
      "group": "Physical tutorial",
      "tier": 3,
      "units": 36,
      "previous": null,
      "source": "Price List 2026!L20",
      "unavailable": false
    },
    {
      "id": "B-21-9",
      "product": "B",
      "level": "Primary 3–4",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 6900,
      "group": "Physical tutorial",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I21",
      "unavailable": false
    },
    {
      "id": "B-21-10",
      "product": "B",
      "level": "Primary 3–4",
      "category": "Lite",
      "unit": "lesson",
      "amount": 6400,
      "group": "Physical tutorial",
      "tier": 1,
      "units": 4,
      "previous": null,
      "source": "Price List 2026!J21",
      "unavailable": false
    },
    {
      "id": "B-21-11",
      "product": "B",
      "level": "Primary 3–4",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 5900,
      "group": "Physical tutorial",
      "tier": 2,
      "units": 12,
      "previous": null,
      "source": "Price List 2026!K21",
      "unavailable": false
    },
    {
      "id": "B-21-12",
      "product": "B",
      "level": "Primary 3–4",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 5500,
      "group": "Physical tutorial",
      "tier": 3,
      "units": 36,
      "previous": null,
      "source": "Price List 2026!L21",
      "unavailable": false
    },
    {
      "id": "B-22-9",
      "product": "B",
      "level": "Primary 5–6",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 7700,
      "group": "Physical tutorial",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I22",
      "unavailable": false
    },
    {
      "id": "B-22-10",
      "product": "B",
      "level": "Primary 5–6",
      "category": "Lite",
      "unit": "lesson",
      "amount": 7300,
      "group": "Physical tutorial",
      "tier": 1,
      "units": 4,
      "previous": null,
      "source": "Price List 2026!J22",
      "unavailable": false
    },
    {
      "id": "B-22-11",
      "product": "B",
      "level": "Primary 5–6",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 6800,
      "group": "Physical tutorial",
      "tier": 2,
      "units": 12,
      "previous": null,
      "source": "Price List 2026!K22",
      "unavailable": false
    },
    {
      "id": "B-22-12",
      "product": "B",
      "level": "Primary 5–6",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 6500,
      "group": "Physical tutorial",
      "tier": 3,
      "units": 36,
      "previous": null,
      "source": "Price List 2026!L22",
      "unavailable": false
    },
    {
      "id": "B-23-9",
      "product": "B",
      "level": "Secondary 1–2 / IP·IB Y1–2",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 8600,
      "group": "Physical tutorial",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I23",
      "unavailable": false
    },
    {
      "id": "B-23-10",
      "product": "B",
      "level": "Secondary 1–2 / IP·IB Y1–2",
      "category": "Lite",
      "unit": "lesson",
      "amount": 8200,
      "group": "Physical tutorial",
      "tier": 1,
      "units": 4,
      "previous": null,
      "source": "Price List 2026!J23",
      "unavailable": false
    },
    {
      "id": "B-23-11",
      "product": "B",
      "level": "Secondary 1–2 / IP·IB Y1–2",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 7600,
      "group": "Physical tutorial",
      "tier": 2,
      "units": 12,
      "previous": null,
      "source": "Price List 2026!K23",
      "unavailable": false
    },
    {
      "id": "B-23-12",
      "product": "B",
      "level": "Secondary 1–2 / IP·IB Y1–2",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 7300,
      "group": "Physical tutorial",
      "tier": 3,
      "units": 36,
      "previous": null,
      "source": "Price List 2026!L23",
      "unavailable": false
    },
    {
      "id": "B-24-9",
      "product": "B",
      "level": "Secondary 3–5",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 8900,
      "group": "Physical tutorial",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I24",
      "unavailable": false
    },
    {
      "id": "B-24-10",
      "product": "B",
      "level": "Secondary 3–5",
      "category": "Lite",
      "unit": "lesson",
      "amount": 8500,
      "group": "Physical tutorial",
      "tier": 1,
      "units": 4,
      "previous": null,
      "source": "Price List 2026!J24",
      "unavailable": false
    },
    {
      "id": "B-24-11",
      "product": "B",
      "level": "Secondary 3–5",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 7800,
      "group": "Physical tutorial",
      "tier": 2,
      "units": 12,
      "previous": null,
      "source": "Price List 2026!K24",
      "unavailable": false
    },
    {
      "id": "B-24-12",
      "product": "B",
      "level": "Secondary 3–5",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 7600,
      "group": "Physical tutorial",
      "tier": 3,
      "units": 36,
      "previous": null,
      "source": "Price List 2026!L24",
      "unavailable": false
    },
    {
      "id": "B-25-9",
      "product": "B",
      "level": "JC / IB / IP Y5–Y6",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 11000,
      "group": "Physical tutorial",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I25",
      "unavailable": false
    },
    {
      "id": "B-25-10",
      "product": "B",
      "level": "JC / IB / IP Y5–Y6",
      "category": "Lite",
      "unit": "lesson",
      "amount": 10500,
      "group": "Physical tutorial",
      "tier": 1,
      "units": 4,
      "previous": null,
      "source": "Price List 2026!J25",
      "unavailable": false
    },
    {
      "id": "B-25-11",
      "product": "B",
      "level": "JC / IB / IP Y5–Y6",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 9700,
      "group": "Physical tutorial",
      "tier": 2,
      "units": 12,
      "previous": null,
      "source": "Price List 2026!K25",
      "unavailable": false
    },
    {
      "id": "B-25-12",
      "product": "B",
      "level": "JC / IB / IP Y5–Y6",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 9400,
      "group": "Physical tutorial",
      "tier": 3,
      "units": 36,
      "previous": null,
      "source": "Price List 2026!L25",
      "unavailable": false
    },
    {
      "id": "B-26-9",
      "product": "B",
      "level": "IB / IP Y3–Y4",
      "category": "Standard / Trial",
      "unit": "lesson",
      "amount": 9900,
      "group": "Physical tutorial",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I26",
      "unavailable": false
    },
    {
      "id": "B-26-10",
      "product": "B",
      "level": "IB / IP Y3–Y4",
      "category": "Lite",
      "unit": "lesson",
      "amount": 9400,
      "group": "Physical tutorial",
      "tier": 1,
      "units": 4,
      "previous": null,
      "source": "Price List 2026!J26",
      "unavailable": false
    },
    {
      "id": "B-26-11",
      "product": "B",
      "level": "IB / IP Y3–Y4",
      "category": "Package (12+ lessons)",
      "unit": "lesson",
      "amount": 8700,
      "group": "Physical tutorial",
      "tier": 2,
      "units": 12,
      "previous": null,
      "source": "Price List 2026!K26",
      "unavailable": false
    },
    {
      "id": "B-26-12",
      "product": "B",
      "level": "IB / IP Y3–Y4",
      "category": "3+ subjects (siblings)",
      "unit": "lesson",
      "amount": 8400,
      "group": "Physical tutorial",
      "tier": 3,
      "units": 36,
      "previous": null,
      "source": "Price List 2026!L26",
      "unavailable": false
    },
    {
      "id": "C-33-9",
      "product": "C",
      "level": "Primary 3–4",
      "category": "Standard / Trial",
      "unit": "class",
      "amount": 4000,
      "group": "C only",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I33",
      "unavailable": false
    },
    {
      "id": "C-33-10",
      "product": "C",
      "level": "Primary 3–4",
      "category": "4 classes",
      "unit": "class",
      "amount": 3800,
      "group": "C only",
      "tier": 1,
      "units": 4,
      "previous": 3450,
      "source": "Price List 2026!J33",
      "unavailable": false
    },
    {
      "id": "C-33-11",
      "product": "C",
      "level": "Primary 3–4",
      "category": "12 classes",
      "unit": "class",
      "amount": 3600,
      "group": "C only",
      "tier": 2,
      "units": 12,
      "previous": 3275,
      "source": "Price List 2026!K33",
      "unavailable": false
    },
    {
      "id": "C-33-12",
      "product": "C",
      "level": "Primary 3–4",
      "category": "24 classes",
      "unit": "class",
      "amount": 3400,
      "group": "C only",
      "tier": 3,
      "units": 24,
      "previous": 3104,
      "source": "Price List 2026!L33",
      "unavailable": false
    },
    {
      "id": "C-34-9",
      "product": "C",
      "level": "Primary 5–6",
      "category": "Standard / Trial",
      "unit": "class",
      "amount": 4800,
      "group": "C only",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I34",
      "unavailable": false
    },
    {
      "id": "C-34-10",
      "product": "C",
      "level": "Primary 5–6",
      "category": "4 classes",
      "unit": "class",
      "amount": 4560,
      "group": "C only",
      "tier": 1,
      "units": 4,
      "previous": 4200,
      "source": "Price List 2026!J34",
      "unavailable": false
    },
    {
      "id": "C-34-11",
      "product": "C",
      "level": "Primary 5–6",
      "category": "12 classes",
      "unit": "class",
      "amount": 4320,
      "group": "C only",
      "tier": 2,
      "units": 12,
      "previous": 3992,
      "source": "Price List 2026!K34",
      "unavailable": false
    },
    {
      "id": "C-34-12",
      "product": "C",
      "level": "Primary 5–6",
      "category": "24 classes",
      "unit": "class",
      "amount": 4080,
      "group": "C only",
      "tier": 3,
      "units": 24,
      "previous": 3779,
      "source": "Price List 2026!L34",
      "unavailable": false
    },
    {
      "id": "C-35-9",
      "product": "C",
      "level": "Secondary 1–2",
      "category": "Standard / Trial",
      "unit": "class",
      "amount": 4800,
      "group": "C only",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I35",
      "unavailable": false
    },
    {
      "id": "C-35-10",
      "product": "C",
      "level": "Secondary 1–2",
      "category": "4 classes",
      "unit": "class",
      "amount": 4560,
      "group": "C only",
      "tier": 1,
      "units": 4,
      "previous": 4200,
      "source": "Price List 2026!J35",
      "unavailable": false
    },
    {
      "id": "C-35-11",
      "product": "C",
      "level": "Secondary 1–2",
      "category": "12 classes",
      "unit": "class",
      "amount": 4320,
      "group": "C only",
      "tier": 2,
      "units": 12,
      "previous": 3992,
      "source": "Price List 2026!K35",
      "unavailable": false
    },
    {
      "id": "C-35-12",
      "product": "C",
      "level": "Secondary 1–2",
      "category": "24 classes",
      "unit": "class",
      "amount": 4080,
      "group": "C only",
      "tier": 3,
      "units": 24,
      "previous": 3779,
      "source": "Price List 2026!L35",
      "unavailable": false
    },
    {
      "id": "C-36-9",
      "product": "C",
      "level": "Secondary 3–4",
      "category": "Standard / Trial",
      "unit": "class",
      "amount": 5100,
      "group": "C only",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I36",
      "unavailable": false
    },
    {
      "id": "C-36-10",
      "product": "C",
      "level": "Secondary 3–4",
      "category": "4 classes",
      "unit": "class",
      "amount": 4845,
      "group": "C only",
      "tier": 1,
      "units": 4,
      "previous": 4450,
      "source": "Price List 2026!J36",
      "unavailable": false
    },
    {
      "id": "C-36-11",
      "product": "C",
      "level": "Secondary 3–4",
      "category": "12 classes",
      "unit": "class",
      "amount": 4590,
      "group": "C only",
      "tier": 2,
      "units": 12,
      "previous": 4225,
      "source": "Price List 2026!K36",
      "unavailable": false
    },
    {
      "id": "C-36-12",
      "product": "C",
      "level": "Secondary 3–4",
      "category": "24 classes",
      "unit": "class",
      "amount": 4335,
      "group": "C only",
      "tier": 3,
      "units": 24,
      "previous": 4004,
      "source": "Price List 2026!L36",
      "unavailable": false
    },
    {
      "id": "C-40-9",
      "product": "C",
      "level": "Primary 3–4",
      "category": "Standard / Trial",
      "unit": "class",
      "amount": 3400,
      "group": "Existing package student",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I40",
      "unavailable": false
    },
    {
      "id": "C-40-10",
      "product": "C",
      "level": "Primary 3–4",
      "category": "4 classes",
      "unit": "class",
      "amount": 3230,
      "group": "Existing package student",
      "tier": 1,
      "units": 4,
      "previous": 2950,
      "source": "Price List 2026!J40",
      "unavailable": false
    },
    {
      "id": "C-40-11",
      "product": "C",
      "level": "Primary 3–4",
      "category": "12 classes",
      "unit": "class",
      "amount": 3060,
      "group": "Existing package student",
      "tier": 2,
      "units": 12,
      "previous": 2800,
      "source": "Price List 2026!K40",
      "unavailable": false
    },
    {
      "id": "C-40-12",
      "product": "C",
      "level": "Primary 3–4",
      "category": "24 classes",
      "unit": "class",
      "amount": 2890,
      "group": "Existing package student",
      "tier": 3,
      "units": 24,
      "previous": 2654,
      "source": "Price List 2026!L40",
      "unavailable": false
    },
    {
      "id": "C-41-9",
      "product": "C",
      "level": "Primary 5–6",
      "category": "Standard / Trial",
      "unit": "class",
      "amount": 4000,
      "group": "Existing package student",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I41",
      "unavailable": false
    },
    {
      "id": "C-41-10",
      "product": "C",
      "level": "Primary 5–6",
      "category": "4 classes",
      "unit": "class",
      "amount": 3800,
      "group": "Existing package student",
      "tier": 1,
      "units": 4,
      "previous": 3450,
      "source": "Price List 2026!J41",
      "unavailable": false
    },
    {
      "id": "C-41-11",
      "product": "C",
      "level": "Primary 5–6",
      "category": "12 classes",
      "unit": "class",
      "amount": 3600,
      "group": "Existing package student",
      "tier": 2,
      "units": 12,
      "previous": 3275,
      "source": "Price List 2026!K41",
      "unavailable": false
    },
    {
      "id": "C-41-12",
      "product": "C",
      "level": "Primary 5–6",
      "category": "24 classes",
      "unit": "class",
      "amount": 3400,
      "group": "Existing package student",
      "tier": 3,
      "units": 24,
      "previous": 3104,
      "source": "Price List 2026!L41",
      "unavailable": false
    },
    {
      "id": "C-42-9",
      "product": "C",
      "level": "Secondary 1–2",
      "category": "Standard / Trial",
      "unit": "class",
      "amount": 4000,
      "group": "Existing package student",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I42",
      "unavailable": false
    },
    {
      "id": "C-42-10",
      "product": "C",
      "level": "Secondary 1–2",
      "category": "4 classes",
      "unit": "class",
      "amount": 3800,
      "group": "Existing package student",
      "tier": 1,
      "units": 4,
      "previous": 3450,
      "source": "Price List 2026!J42",
      "unavailable": false
    },
    {
      "id": "C-42-11",
      "product": "C",
      "level": "Secondary 1–2",
      "category": "12 classes",
      "unit": "class",
      "amount": 3600,
      "group": "Existing package student",
      "tier": 2,
      "units": 12,
      "previous": 3275,
      "source": "Price List 2026!K42",
      "unavailable": false
    },
    {
      "id": "C-42-12",
      "product": "C",
      "level": "Secondary 1–2",
      "category": "24 classes",
      "unit": "class",
      "amount": 3400,
      "group": "Existing package student",
      "tier": 3,
      "units": 24,
      "previous": 3104,
      "source": "Price List 2026!L42",
      "unavailable": false
    },
    {
      "id": "C-43-9",
      "product": "C",
      "level": "Secondary 3–4",
      "category": "Standard / Trial",
      "unit": "class",
      "amount": 4300,
      "group": "Existing package student",
      "tier": 0,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!I43",
      "unavailable": false
    },
    {
      "id": "C-43-10",
      "product": "C",
      "level": "Secondary 3–4",
      "category": "4 classes",
      "unit": "class",
      "amount": 4085,
      "group": "Existing package student",
      "tier": 1,
      "units": 4,
      "previous": 3700,
      "source": "Price List 2026!J43",
      "unavailable": false
    },
    {
      "id": "C-43-11",
      "product": "C",
      "level": "Secondary 3–4",
      "category": "12 classes",
      "unit": "class",
      "amount": 3870,
      "group": "Existing package student",
      "tier": 2,
      "units": 12,
      "previous": 3517,
      "source": "Price List 2026!K43",
      "unavailable": false
    },
    {
      "id": "C-43-12",
      "product": "C",
      "level": "Secondary 3–4",
      "category": "24 classes",
      "unit": "class",
      "amount": 3655,
      "group": "Existing package student",
      "tier": 3,
      "units": 24,
      "previous": 3329,
      "source": "Price List 2026!L43",
      "unavailable": false
    },
    {
      "id": "D-51-9",
      "product": "D",
      "level": "Primary 1–2",
      "category": "1 subject",
      "unit": "annual package",
      "amount": 35500,
      "group": "Standard",
      "tier": 0,
      "units": 1,
      "previous": 33800,
      "source": "Price List 2026!I51",
      "unavailable": false
    },
    {
      "id": "D-51-10",
      "product": "D",
      "level": "Primary 1–2",
      "category": "2 subjects",
      "unit": "annual package",
      "amount": 62500,
      "group": "Standard",
      "tier": 1,
      "units": 1,
      "previous": 59800,
      "source": "Price List 2026!J51",
      "unavailable": false
    },
    {
      "id": "D-51-11",
      "product": "D",
      "level": "Primary 1–2",
      "category": "3 subjects",
      "unit": "annual package",
      "amount": 79900,
      "group": "Standard",
      "tier": 2,
      "units": 1,
      "previous": 75800,
      "source": "Price List 2026!K51",
      "unavailable": false
    },
    {
      "id": "D-51-12",
      "product": "D",
      "level": "Primary 1–2",
      "category": "4 subjects",
      "unit": "annual package",
      "amount": null,
      "group": "Standard",
      "tier": 3,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!L51",
      "unavailable": true
    },
    {
      "id": "D-52-9",
      "product": "D",
      "level": "Primary 3–6",
      "category": "1 subject",
      "unit": "annual package",
      "amount": 48100,
      "group": "Standard",
      "tier": 0,
      "units": 1,
      "previous": 45800,
      "source": "Price List 2026!I52",
      "unavailable": false
    },
    {
      "id": "D-52-10",
      "product": "D",
      "level": "Primary 3–6",
      "category": "2 subjects",
      "unit": "annual package",
      "amount": 84700,
      "group": "Standard",
      "tier": 1,
      "units": 1,
      "previous": 80800,
      "source": "Price List 2026!J52",
      "unavailable": false
    },
    {
      "id": "D-52-11",
      "product": "D",
      "level": "Primary 3–6",
      "category": "3 subjects",
      "unit": "annual package",
      "amount": 108200,
      "group": "Standard",
      "tier": 2,
      "units": 1,
      "previous": 102800,
      "source": "Price List 2026!K52",
      "unavailable": false
    },
    {
      "id": "D-52-12",
      "product": "D",
      "level": "Primary 3–6",
      "category": "4 subjects",
      "unit": "annual package",
      "amount": 134700,
      "group": "Standard",
      "tier": 3,
      "units": 1,
      "previous": 127800,
      "source": "Price List 2026!L52",
      "unavailable": false
    },
    {
      "id": "D-53-9",
      "product": "D",
      "level": "Secondary 1–4",
      "category": "1 subject",
      "unit": "annual package",
      "amount": 60700,
      "group": "Standard",
      "tier": 0,
      "units": 1,
      "previous": 57800,
      "source": "Price List 2026!I53",
      "unavailable": false
    },
    {
      "id": "D-53-10",
      "product": "D",
      "level": "Secondary 1–4",
      "category": "2 subjects",
      "unit": "annual package",
      "amount": 106800,
      "group": "Standard",
      "tier": 1,
      "units": 1,
      "previous": 101800,
      "source": "Price List 2026!J53",
      "unavailable": false
    },
    {
      "id": "D-53-11",
      "product": "D",
      "level": "Secondary 1–4",
      "category": "3 subjects",
      "unit": "annual package",
      "amount": 136600,
      "group": "Standard",
      "tier": 2,
      "units": 1,
      "previous": 129800,
      "source": "Price List 2026!K53",
      "unavailable": false
    },
    {
      "id": "D-53-12",
      "product": "D",
      "level": "Secondary 1–4",
      "category": "4 subjects",
      "unit": "annual package",
      "amount": 170000,
      "group": "Standard",
      "tier": 3,
      "units": 1,
      "previous": 161800,
      "source": "Price List 2026!L53",
      "unavailable": false
    },
    {
      "id": "D-59-9",
      "product": "D",
      "level": "Primary 1–2",
      "category": "1 subject",
      "unit": "annual package",
      "amount": 28400,
      "group": "Aspire Hub student",
      "tier": 0,
      "units": 1,
      "previous": 27040,
      "source": "Price List 2026!I59",
      "unavailable": false
    },
    {
      "id": "D-59-10",
      "product": "D",
      "level": "Primary 1–2",
      "category": "2 subjects",
      "unit": "annual package",
      "amount": 50000,
      "group": "Aspire Hub student",
      "tier": 1,
      "units": 1,
      "previous": 47840,
      "source": "Price List 2026!J59",
      "unavailable": false
    },
    {
      "id": "D-59-11",
      "product": "D",
      "level": "Primary 1–2",
      "category": "3 subjects",
      "unit": "annual package",
      "amount": 63900,
      "group": "Aspire Hub student",
      "tier": 2,
      "units": 1,
      "previous": 60640,
      "source": "Price List 2026!K59",
      "unavailable": false
    },
    {
      "id": "D-59-12",
      "product": "D",
      "level": "Primary 1–2",
      "category": "4 subjects",
      "unit": "annual package",
      "amount": null,
      "group": "Aspire Hub student",
      "tier": 3,
      "units": 1,
      "previous": null,
      "source": "Price List 2026!L59",
      "unavailable": true
    },
    {
      "id": "D-60-9",
      "product": "D",
      "level": "Primary 3–6",
      "category": "1 subject",
      "unit": "annual package",
      "amount": 38500,
      "group": "Aspire Hub student",
      "tier": 0,
      "units": 1,
      "previous": 36640,
      "source": "Price List 2026!I60",
      "unavailable": false
    },
    {
      "id": "D-60-10",
      "product": "D",
      "level": "Primary 3–6",
      "category": "2 subjects",
      "unit": "annual package",
      "amount": 67800,
      "group": "Aspire Hub student",
      "tier": 1,
      "units": 1,
      "previous": 64640,
      "source": "Price List 2026!J60",
      "unavailable": false
    },
    {
      "id": "D-60-11",
      "product": "D",
      "level": "Primary 3–6",
      "category": "3 subjects",
      "unit": "annual package",
      "amount": 86600,
      "group": "Aspire Hub student",
      "tier": 2,
      "units": 1,
      "previous": 82240,
      "source": "Price List 2026!K60",
      "unavailable": false
    },
    {
      "id": "D-60-12",
      "product": "D",
      "level": "Primary 3–6",
      "category": "4 subjects",
      "unit": "annual package",
      "amount": 107800,
      "group": "Aspire Hub student",
      "tier": 3,
      "units": 1,
      "previous": 102240,
      "source": "Price List 2026!L60",
      "unavailable": false
    },
    {
      "id": "D-61-9",
      "product": "D",
      "level": "Secondary 1–4",
      "category": "1 subject",
      "unit": "annual package",
      "amount": 48600,
      "group": "Aspire Hub student",
      "tier": 0,
      "units": 1,
      "previous": 46240,
      "source": "Price List 2026!I61",
      "unavailable": false
    },
    {
      "id": "D-61-10",
      "product": "D",
      "level": "Secondary 1–4",
      "category": "2 subjects",
      "unit": "annual package",
      "amount": 85500,
      "group": "Aspire Hub student",
      "tier": 1,
      "units": 1,
      "previous": 81440,
      "source": "Price List 2026!J61",
      "unavailable": false
    },
    {
      "id": "D-61-11",
      "product": "D",
      "level": "Secondary 1–4",
      "category": "3 subjects",
      "unit": "annual package",
      "amount": 109400,
      "group": "Aspire Hub student",
      "tier": 2,
      "units": 1,
      "previous": 103840,
      "source": "Price List 2026!K61",
      "unavailable": false
    },
    {
      "id": "D-61-12",
      "product": "D",
      "level": "Secondary 1–4",
      "category": "4 subjects",
      "unit": "annual package",
      "amount": 136100,
      "group": "Aspire Hub student",
      "tier": 3,
      "units": 1,
      "previous": 129440,
      "source": "Price List 2026!L61",
      "unavailable": false
    }
  ],
  "teacher": {
    "A": 40,
    "B": 40,
    "C": 40,
    "D": 0
  },
  "rates": {
    "initial": {
      "Physical Centre": {
        "A": [
          0,
          0,
          0,
          0
        ],
        "B": [
          0,
          0,
          0,
          0
        ],
        "C": [
          5,
          0,
          10,
          0
        ],
        "D": [
          15,
          0,
          25,
          0
        ]
      },
      "Online": {
        "A": [
          null,
          null,
          null,
          null
        ],
        "B": [
          null,
          null,
          null,
          null
        ]
      },
      "Cold Call": {
        "A": [
          5,
          3,
          0,
          5
        ],
        "B": [
          5,
          3,
          0,
          5
        ],
        "C": [
          5,
          3,
          7,
          0
        ],
        "D": [
          15,
          10,
          15,
          0
        ]
      }
    },
    "renewal": {
      "Physical Centre": {
        "A": [
          null,
          null,
          null,
          null
        ],
        "B": [
          null,
          null,
          null,
          null
        ],
        "C": [
          null,
          null,
          null,
          null
        ],
        "D": [
          null,
          null,
          null,
          null
        ]
      },
      "Online": {
        "A": [
          null,
          null,
          null,
          null
        ],
        "B": [
          null,
          null,
          null,
          null
        ]
      },
      "Cold Call": {
        "A": [
          null,
          null,
          null,
          null
        ],
        "B": [
          null,
          null,
          null,
          null
        ],
        "C": [
          null,
          null,
          null,
          null
        ],
        "D": [
          null,
          null,
          null,
          null
        ]
      }
    },
    "upsell": {
      "Physical Centre": {
        "A": [
          null,
          null,
          null,
          null
        ],
        "B": [
          null,
          null,
          null,
          null
        ],
        "C": [
          null,
          null,
          null,
          null
        ],
        "D": [
          null,
          null,
          null,
          null
        ]
      },
      "Online": {
        "A": [
          null,
          null,
          null,
          null
        ],
        "B": [
          null,
          null,
          null,
          null
        ]
      },
      "Cold Call": {
        "A": [
          null,
          null,
          null,
          null
        ],
        "B": [
          null,
          null,
          null,
          null
        ],
        "C": [
          null,
          null,
          null,
          null
        ],
        "D": [
          null,
          null,
          null,
          null
        ]
      }
    }
  }
};
